{
  "hash": "2ae2b7ca998ecf6e5e4988c6ddadd554",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Introduction to proteomics data analysis - MaxQuant Data Dependent Acquisition spike-in study\"\ncode-tools: true\nauthor:\n  - name: Lieven Clement, Stijn Vandenbulcke, Oliver M. Crook and Christophe Vanderaa\n    orcid: 0000-0002-9050-4370\n    affiliation: \n      - name: Ghent University\n---\n\n# Introduction\n\nLabel-Free Quantitative mass spectrometry based workflows for differential \nexpression (DE) analysis of proteins is often challenging due to \npeptide-specific effects and context-sensitive missingness of peptide \nintensities.\n\n- `msqrob2` provides  peptide-based workflows that can assess for DE directly \nfrom peptide intensities and outperform summarisation methods which first \naggregate MS1 peptide intensities to protein intensities before DE analysis.\nHowever, they are computationally expensive, often hard to understand for the \nnon-specialised end-user, and they do not provide protein summaries, which are \nimportant for visualisation or downstream processing.\n\n- `msqrob2` therefore also proposes a novel summarisation strategy, which \nestimates MSqRob's model parameters in a two-stage procedure circumventing the \ndrawbacks of peptide-based workflows.\n\n- the summarisation based workflow in `msqrob2` maintains MSqRob's superior \nperformance, while providing useful protein expression summaries for plotting \nand downstream analysis.\nSummarising peptide to protein intensities considerably reduces the \ncomputational complexity, the memory footprint and the model complexity.\nMoreover, it renders the analysis framework to become modular, providing users \nthe flexibility to develop workflows tailored towards specific applications.\n\nIn this vignette we will demonstrate how to perform  `msqrob`'s summarisation \nbased workflow  starting from a MaxQuant search on a subset of the cptac\nspike-in study.\n\nTechnical details on our methods, and, examples on the analysis of more complex \ndesigns and on our peptide-based workflows can be found on our companion website \n[msqrob2 book](https://statomics.github.io/msqrob2book).\n\n# Background\n\nThis case-study is a subset of the data of the 6th study of the Clinical\nProteomic Technology Assessment for Cancer (CPTAC).\nIn this experiment, the authors spiked the Sigma Universal Protein Standard\nmixture 1 (UPS1) containing 48 different human proteins in a protein background\nof 60 ng/$\\mu$L Saccharomyces cerevisiae strain BY4741.\nTwo different spike-in concentrations were used:\n6A (0.25 fmol UPS1 proteins/$\\mu$L) and 6B (0.74 fmol UPS1 proteins/$\\mu$L) [5].\nWe limited ourselves to the data of LTQ-Orbitrap W at site 56.\nThe data were searched with MaxQuant version 1.5.2.8, and\ndetailed search settings were described in Goeminne et al. (2016) [1].\nThree replicates are available for each concentration.\n\n# Load packages\n\nWe load the `msqrob2` package, along with additional packages for\ndata manipulation and visualisation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages({\nlibrary(\"QFeatures\")  \nlibrary(\"dplyr\") \nlibrary(\"tidyr\")\nlibrary(\"ggplot2\")\nlibrary(\"msqrob2\")    \nlibrary(\"stringr\")\nlibrary(\"ExploreModelMatrix\")\nlibrary(\"kableExtra\")\nlibrary(\"ComplexHeatmap\")\nlibrary(\"scater\")\n})\n```\n:::\n\n\n# Data\n\n## Peptide table\n\nWe first import the data from the peptide.txt file. This is the file containing\nyour peptide-level intensities searched by MaxQuant search,\nthis peptide.txt file can be found by default in the\n\"path_to_raw_files/combined/txt/\" folder from the MaxQuant output,\nwith \"path_to_raw_files\" the folder where the raw files were saved.\nIn this vignette, we use a MaxQuant peptide file which is a subset\nof the cptac study. \nThis data is available in \n[msqrob2data](https://github.com/statOmics/msqrob2data) GitHub repository.\nTo import the data we use the `QFeatures` package.\n\nWe generate the object peptideFile with the path to the peptide.txt file.\nThis can be a path to the data on the web or a path to data on your local \ncomputer. \n\n\n::: {.cell}\n\n```{.r .cell-code}\npeptideFile <- \"https://github.com/statOmics/msqrob2data/raw/refs/heads/main/dda/cptacAvsB_lab3/peptides.txt\"\n```\n:::\n\n\n\nWe will import the data using the `fread` function of the data.table package. \nWe set the `check.names` argument equal to  `TRUE` so that all column names are \nretrieved using the `$` operator.  \nWe also use argument integer64 = \"double\" because `readQFeatures` from the \n`QFeatures` package does not process 64-bit integers correctly. \n\n\n::: {.cell}\n\n```{.r .cell-code}\npeptides <- data.table::fread(peptideFile, \n                              check.names = TRUE, \n                              integer64 = \"double\")\nhead(peptides)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Sequence N.term.cleavage.window C.term.cleavage.window\n               <char>                 <char>                 <char>\n1: AAAAGAGGAGDSGDAVTK       EHQHDEQKAAAAGAGG       DSGDAVTKIGSEDVKL\n2:          AAAALAGGK       QQLSKAAKAAAALAGG       AAALAGGKKSKKKWSK\n3:         AAAALAGGKK       QQLSKAAKAAAALAGG       AALAGGKKSKKKWSKK\n4:       AAADALSDLEIK       MPKETPSKAAADALSD       ALSDLEIKDSKSNLNK\n5:    AAADALSDLEIKDSK       MPKETPSKAAADALSD       DLEIKDSKSNLNKELE\n6:           AAAEEFQR       RERKEREKAAAEEFQR       AAAEEFQRQQELLRQQ\n   Amino.acid.before First.amino.acid Second.amino.acid Second.last.amino.acid\n              <char>           <char>            <char>                 <char>\n1:                 K                A                 A                      T\n2:                 K                A                 A                      G\n3:                 K                A                 A                      K\n4:                 K                A                 A                      I\n5:                 K                A                 A                      S\n6:                 K                A                 A                      Q\n   Last.amino.acid Amino.acid.after A.Count R.Count N.Count D.Count C.Count\n            <char>           <char>   <int>   <int>   <int>   <int>   <int>\n1:               K                I       7       0       0       2       0\n2:               K                K       5       0       0       0       0\n3:               K                S       5       0       0       0       0\n4:               K                D       4       0       0       2       0\n5:               K                S       4       0       0       3       0\n6:               R                Q       3       1       0       0       0\n   Q.Count E.Count G.Count H.Count I.Count L.Count K.Count M.Count F.Count\n     <int>   <int>   <int>   <int>   <int>   <int>   <int>   <int>   <int>\n1:       0       0       5       0       0       0       1       0       0\n2:       0       0       2       0       0       1       1       0       0\n3:       0       0       2       0       0       1       2       0       0\n4:       0       1       0       0       1       2       1       0       0\n5:       0       1       0       0       1       2       2       0       0\n6:       1       2       0       0       0       0       0       0       1\n   P.Count S.Count T.Count W.Count Y.Count V.Count U.Count Length\n     <int>   <int>   <int>   <int>   <int>   <int>   <int>  <int>\n1:       0       1       1       0       0       1       0     18\n2:       0       0       0       0       0       0       0      9\n3:       0       0       0       0       0       0       0     10\n4:       0       1       0       0       0       0       0     12\n5:       0       2       0       0       0       0       0     15\n6:       0       0       0       0       0       0       0      8\n   Missed.cleavages      Mass                                    Proteins\n              <int>     <num>                                      <char>\n1:                0 1445.6746                        sp|P38915|SPT8_YEAST\n2:                0  728.4181 sp|Q3E792|RS25A_YEAST;sp|P0C0T4|RS25B_YEAST\n3:                1  856.5131 sp|Q3E792|RS25A_YEAST;sp|P0C0T4|RS25B_YEAST\n4:                0 1215.6347                        sp|P09938|RIR2_YEAST\n5:                1 1545.7886                        sp|P09938|RIR2_YEAST\n6:                0  920.4352                       sp|P53075|SHE10_YEAST\n   Leading.razor.protein Start.position End.position Unique..Groups.\n                  <char>          <int>        <int>          <char>\n1:  sp|P38915|SPT8_YEAST             97          114             yes\n2: sp|Q3E792|RS25A_YEAST             13           21             yes\n3: sp|Q3E792|RS25A_YEAST             13           22             yes\n4:  sp|P09938|RIR2_YEAST              9           20             yes\n5:  sp|P09938|RIR2_YEAST              9           23             yes\n6: sp|P53075|SHE10_YEAST            538          545             yes\n   Unique..Proteins. Charges        PEP   Score Identification.type.6A_7\n              <char>  <char>      <num>   <num>                   <char>\n1:               yes       2 1.1800e-05  82.942                 By MS/MS\n2:                no       2 7.4600e-06 134.810                 By MS/MS\n3:                no       2 3.3100e-09 143.730                 By MS/MS\n4:               yes       2 9.1600e-23 182.230                 By MS/MS\n5:               yes       3 1.5319e-04  73.927                 By MS/MS\n6:               yes       2 1.7588e-02  79.474              By matching\n   Identification.type.6A_8 Identification.type.6A_9 Identification.type.6B_7\n                     <char>                   <char>                   <char>\n1:                 By MS/MS                 By MS/MS              By matching\n2:                 By MS/MS                 By MS/MS                 By MS/MS\n3:                 By MS/MS                 By MS/MS                 By MS/MS\n4:              By matching                 By MS/MS                 By MS/MS\n5:                 By MS/MS                 By MS/MS                 By MS/MS\n6:              By matching              By matching              By matching\n   Identification.type.6B_8 Identification.type.6B_9 Experiment.6A_7\n                     <char>                   <char>           <int>\n1:                 By MS/MS                 By MS/MS               1\n2:                 By MS/MS                 By MS/MS               2\n3:                 By MS/MS                 By MS/MS               1\n4:              By matching              By matching               1\n5:                 By MS/MS                 By MS/MS               1\n6:              By matching              By matching              NA\n   Experiment.6A_8 Experiment.6A_9 Experiment.6B_7 Experiment.6B_8\n             <int>           <int>           <int>           <int>\n1:               1               1              NA               1\n2:               1               1               2               1\n3:               1               1               1               1\n4:               1               1               1               1\n5:               1               1               1               1\n6:              NA               1              NA              NA\n   Experiment.6B_9 Intensity Intensity.6A_7 Intensity.6A_8 Intensity.6A_9\n             <int>     <num>          <num>          <num>          <num>\n1:               1   1190800              0              0          66760\n2:               2 280990000        2441300        1220000        1337600\n3:               1  33360000        1029200         668040         638990\n4:               1  54622000         515460         670780         712140\n5:               1  18910000         331130         420900         365560\n6:               1   1158600              0              0          51558\n   Intensity.6B_7 Intensity.6B_8 Intensity.6B_9 Reverse Potential.contaminant\n            <num>          <num>          <num>  <char>                <char>\n1:              0          37436              0                              \n2:        2850900         935580        1606200                              \n3:         777030         641270         562840                              \n4:         426580         620510         737780                              \n5:         329250         380820         414490                              \n6:              0              0          76970                              \n      id Protein.group.IDs Mod..peptide.IDs\n   <int>            <char>           <char>\n1:     0               859                0\n2:     1               230                1\n3:     2               230                2\n4:     3               229                3\n5:     4               229                4\n6:     5              1143                5\n                                                                                                                                                                         Evidence.IDs\n                                                                                                                                                                               <char>\n1:                                                                                                                      0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;17;18;19;20;21;22;23\n2:                              24;25;26;27;28;29;30;31;32;33;34;35;36;37;38;39;40;41;42;43;44;45;46;47;48;49;50;51;52;53;54;55;56;57;58;59;60;61;62;63;64;65;66;67;68;69;70;71;72;73\n3:                                                                                                         74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;89;90;91;92;93;94;95;96;97;98\n4: 99;100;101;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;128;129;130;131;132;133;134;135;136;137;138;139;140;141;142;143\n5:                144;145;146;147;148;149;150;151;152;153;154;155;156;157;158;159;160;161;162;163;164;165;166;167;168;169;170;171;172;173;174;175;176;177;178;179;180;181;182;183;184\n6:                                                                                                                                            185;186;187;188;189;190;191;192;193;194\n                                                                                                          MS.MS.IDs\n                                                                                                             <char>\n1:                                                                                              0;1;2;3;4;5;6;7;8;9\n2:                                                      10;11;12;13;14;15;16;17;18;19;20;21;22;23;24;25;26;27;28;29\n3:                                                   30;31;32;33;34;35;36;37;38;39;40;41;42;43;44;45;46;47;48;49;50\n4:            51;52;53;54;55;56;57;58;59;60;61;62;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84\n5: 85;86;87;88;89;90;91;92;93;94;95;96;97;98;99;100;101;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116\n6:                                                                                                          117;118\n   Best.MS.MS Oxidation..M..site.IDs MS.MS.Count\n        <int>                 <char>       <int>\n1:          0                                 10\n2:         21                                 18\n3:         31                                 21\n4:         72                                 29\n5:         94                                 32\n6:        117                                  2\n```\n\n\n:::\n:::\n\n\nEach row in the peptide data table contains information about one peptide \n(the table above shows the first 6 rows). The columns contains various \ndescriptors about the peptide, such as its sequence, its charge, the amino acid \ncomposition, etc. Some of these columns (those starting with `Intensity `) \ncontain the quantification values for each sample. The table format where the \nquantitative values for each sample are contained in a separate column is \ndepicted as the \"wide format\", as opposed to the \"long format\" \n(e.g., the [PSM table]).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantCols <- grep(\"Intensity[.]\", names(peptides), value = TRUE)\n```\n:::\n\n\nUnlike for real experiments, we know the ground truth for this dataset: UPS\nproteins were spiked in at different concentrations and are thus differentially \nabundant (DA, spiked in). \nYeast proteins consist of the background proteome that is the same in all \nsamples and are thus non-DA.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\npeptides <- peptides |> \n  mutate(species = grepl(pattern = \"UPS\",Proteins) |> \n           as.factor() |>\n           recode(\"TRUE\"=\"ups\",\"FALSE\" = \"yeast\"))\n```\n:::\n\n\n## Sample annotation \n\nEach row in the annotation table contains information about one sample. The \ncolumns contain various descriptors about the sample, such as the name of the \nsample or the MS run, the treatment (here the spike-in condition), or any other \nbiological or technical information that may impact the data quality or the \nquantification. Without an annotation table, no analysis can be performed. The \nsample annotations are generated by the researcher. In this example, the \nannotations are extracted from the sample names, although reporting a detailed \ndesign of experiments in a table is better practice.\n\n1. We first generate a variable quantCols, which contain the names of the \nquantification columns. \n2. Next we generate variable `sampleId`, to pinpoint the different samples in \nthe dataset. Since all quantification columns start with the generic string \n`Intensity 6` we replace the string with an empty string `\"\"` so we keep the \nlast 3 characters to refer to the sample. \n3. We construct a variable condition, by using the first letter of the \nsampleId, which refers to the spikein condition. \n4. We construct a variable rep, by using the third letter of the \nsampleId.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(annot <- data.frame(quantCols = quantCols) |> #1.\n  mutate(sampleId = gsub(\"Intensity[.]6\",\"\", quantCols), #2. \n         condition = substr(sampleId,1,1), #3.\n         rep = substr(sampleId, 3, 3)) #4.\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       quantCols sampleId condition rep\n1 Intensity.6A_7      A_7         A   7\n2 Intensity.6A_8      A_8         A   8\n3 Intensity.6A_9      A_9         A   9\n4 Intensity.6B_7      B_7         B   7\n5 Intensity.6B_8      B_8         B   8\n6 Intensity.6B_9      B_9         B   9\n```\n\n\n:::\n:::\n\n\n## Convert to QFeatures\n\n\nThe `readQFeatures()` enables a seamless conversion of tabular data into a \n`QFeatures` object. We provide the peptide table and the sample annotation table. \nThe function will use the `quantCols` column in the sample annotation table to \nunderstand which columns in `peptides` contain the quantitative values, and \nautomatically link the corresponding sample annotation with the quantitative \nvalues. We also tell the function to use the `Sequence` column as peptide \nidentifier, which will be used as rownames. See `?readQFeatures()` for more \ndetails.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(qf <- readQFeatures(assayData = peptides, \n                     colData = annot,\n                     name = \"peptides\",\n                     fnames = \"Sequence\")\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking arguments.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading data as a 'SummarizedExperiment' object.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFormatting sample annotations (colData).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFormatting data as a 'QFeatures' object.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting assay rownames.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAn instance of class QFeatures (type: bulk) with 1 set:\n\n [1] peptides: SummarizedExperiment with 11466 rows and 6 columns \n```\n\n\n:::\n:::\n\n\n# Data preprocessing \n\nSince we have a `QFeatures` object, we can directly make use of `QFeatures’` \ndata preprocessing functionality. A major advantage of QFeatures is that it provides\nthe power to build highly modular workflows, where each step is carried out by a \ndedicated function with a large choice of available methods and parameters. This \nmeans that users can adapt the workflow to their specific use case and their \nspecific needs.\n\n## Encoding missing values\n\nThe first preprocessing step is to correctly encode the missing values. \nIt is important that missing values are encoded using `NA`. For instance, \nnon-observed values should not be encoded with a zero because true zeros \n(the proteomic feature is absent from the sample) cannot be distinguished from \ntechnical zeros (the feature was missed by the instrument or could not be \nidentified). We therefore replace any zero in the quantitative data with an `NA`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- zeroIsNA(qf, \"peptides\") # convert 0 to NA\n```\n:::\n\n\nNote that `msqrob2` can handle missing data without having to rely on hard-to-verify imputation assumptions, which is our general recommendation. However, `msqrob2` does not prevent users from using imputation, which can be performed with `impute()` from the QFeatures package. \n\n## $\\log_2$ transformation\n\nWe perform log2-transformation with `logTransform()` from the `QFeatures` \npackage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- logTransform(qf, base = 2, i = \"peptides\", name = \"peptides_log\")\n```\n:::\n\n\n\n## Peptide-Filtering\n\nFiltering removes low-quality and unreliable peptides that would otherwise introduce noise and artefacts in the data. \n\n### Remove failed protein inference\nWe remove peptides that could not be mapped to a protein. We also remove peptides that cannot be uniquely mapped to a single protein because their sequence is shared across multiple proteins. This often occurs for homologs or for proteins that share similar functional domains. Shared peptides are often mapped to protein groups, which are the set of proteins that share the given peptides. Protein groups are encoded by appending the constituting protein identifiers, separated by a `\";\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- filterFeatures(\n  qf, ~ Proteins != \"\" & ## Remove failed protein inference\n    !grepl(\";\", Proteins)) ## Remove protein groups\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n'Proteins' found in 2 out of 2 assay(s).\n```\n\n\n:::\n:::\n\n\n### Remove reverse sequences and contaminants\n\nWe now remove the peptides that map to decoy sequences or to\ncontaminants proteins. In our `peptide.txt` \nfile decoys and contaminants are indicated with a \"+\" character in the \ncolumn `Reverse` and `Potential.contaminant`, respectively. \nNote, that depending on the version of MaxQuant the name of the contaminant variable differs (e.g. `Contaminant` or `Potential contaminant`). \nNote, that while reading in the `peptides` table spaces in the column names are replaced by a dot. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- filterFeatures(qf, ~ Reverse != \"+\" & ## Remove decoys\n                          Potential.contaminant != \"+\") ## Remove contaminants\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n'Reverse' found in 2 out of 2 assay(s).'Potential.contaminant' found in 2 out of 2 assay(s).\n```\n\n\n:::\n:::\n\n\n### Remove highly missing peptides\n\nThe data are characterised by a high proportion of missing values as\nreported by `nNA()` from the `QFeatures` package. The function\ncomputes the number and the proportion of missing values across\npeptides, samples or for the whole data set and return a list of three\ntables called `nNArows`, `nNAcols`, and `nNA`, respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnNaRes <- nNA(qf, \"peptides\")\nrange(nNaRes$nNAcols$pNA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4245165 0.4963918\n```\n\n\n:::\n:::\n\n\nThe samples contain between 42.5%\nand 49.6% missing values. The\nmissingness within each peptide is more variable, with most peptides\nfound across all samples (`nNA` is 0) and others that could not be\nquantified in any sample (`nNA` is 6), as depicted\nby the histogram below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(nNaRes$nNArows) |> \n  ggplot() +\n  aes(x = nNA) +\n  geom_histogram() +\n  ggtitle(\"Number of missing values for each peptide\") +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](cptac_files/figure-html/plot_NA_features-1.png){width=672}\n:::\n:::\n\n\n\nWe keep peptides that were observed at least 3 times out of the $n\n= 6$ samples, so that we can estimate the peptide characteristics. We tolerate \nthe following proportion of NAs:\n$\\text{pNA} = \\frac{(n - 3)}{n} = 0.5$, so we keep peptides that\nare observed in at least 50% of the samples, which corresponds to one treatment \ncondition. \nThis is an arbitrary value that may need to be adjusted depending on \nthe experiment and the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnObs <- 3\nn <- ncol(qf[[\"peptides_log\"]])\n(qf <- filterNA(qf, i = \"peptides_log\", pNA = (n - nObs) / n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAn instance of class QFeatures (type: bulk) with 2 sets:\n\n [1] peptides: SummarizedExperiment with 10393 rows and 6 columns \n [2] peptides_log: SummarizedExperiment with 5910 rows and 6 columns \n```\n\n\n:::\n:::\n\n\nWe keep 5910 peptides upon filtering.\n\n## Normalisation{#sec-norm}\n\nThe most common objective of MS-based proteomics experiments is to\nunderstand the biological changes in protein abundance between\nexperimental conditions. However, changes in measurements between\ngroups can be caused due to technical factors. For instance, there are\nsystematic fluctuations from run-to-run that shift the measured\nintensity distribution. We can this explore as follows:\n\n1. We extract the sets containing the log transformed data. This is \nperformed using `QFeatures`' 3-way subsetting.\n2. We use `longForm()` to convert the `QFeatures` object into a long\ntable, including all `colData` for filtering and\ncolouring.\n3. We visualise the density of the quantitative values within each\nsample. We colour each sample based on its spike-in condition.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf[, , \"peptides_log\"] |> #1.\n  longForm(colvars = colnames(colData(qf))) |>  #2. \n  data.frame() |> \n  filter(!is.na(value)) |>\n  ggplot() + #3.\n  aes(x = value,\n      colour = condition,\n      group = colname) +\n  geom_density() +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nharmonizing input:\n  removing 6 sampleMap rows not in names(experiments)\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](cptac_files/figure-html/normalisation_needed-1.png){width=672}\n:::\n:::\n\n\nEven in this clean synthetic data set (same yeast background with \nsome spiked UPS proteins), the marginal precursor intensity\ndistributions across samples are not well aligned. Ignoring this\neffect will increase the noise and reduce the statistical power of the\nexperiment, and may also, in case of unbalanced designs, introduce\nconfounding effects that will bias the results.\n\nThere are many ways to perform the normalisation, e.g.  \nmedian centering is a popular choice. \nIf we subtract the sample median at the log scale from each precursor \nlog2 intensity, this basically boils down to calculating log-ratios between\nthe precursor intensity and its sample median. \nHere, we will use the Median of Ratios method of DESeq2, which was originally\ndeveloped for RNA-seq data analysis and can also correct for differences in\ncomposition of the proteomes in the different samples.\nThe method first calculates a pseudo-reference sample (row-wise mean of log2\nintensities, which corresponds to the log2 transformed geometric mean), then\ncalculates log2 ratios of each sample w.r.t. the pseudo-reference, and finally\ntakes the column wise median of these log2 ratios to obtain the sample-based\nnormalisation factor on the log2 scale. This procedure is implemented in the\n`msqrob2` function `nfLogMedianOfRatios`.\n\nNote that users can also use all normalisation functions that are provided in \nQFeatures, i.e. by replacing the sweep function by `QFeatures::normalize`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- sweep( #Subtract log2 norm factor column-by-column (MARGIN = 2)\n  qf,\n  MARGIN = 2,\n  STATS = nfLogMedianOfRatios(qf,\"peptides_log\"),\n  i = \"peptides_log\",\n  name = \"peptides_norm\"\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThis function aims to calculate norm factors on a log scale, \n          the input data are assumed to be on the log-scale!\n```\n\n\n:::\n:::\n\n\n\nWe explore the effect of the global normalisation in the subsequent plot. \n\nFormally, the function applies the following operation on each sample\n$i$ across all precursors $p$:\n\n$$\ny_{ip}^{\\text{norm}} = y_{ip} - nf_i\n$$\n\nwith $y_{ip}$ the log2-transformed intensities and $nf_i$ the log2-transformed\nnorm factor. Upon normalisation, we can see that the distribution of the\n$y_{ip}^{\\text{norm}}$ nicely overlap (using the same code as above)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf[, , \"peptides_norm\"] |>\n  longForm(colvars = colnames(colData(qf))) |> \n  data.frame() |> \n  filter(!is.na(value)) |>\n  ggplot() + \n  aes(x = value,\n      colour = condition,\n      group = colname) +\n  geom_density() +\n  labs(subtitle = \"Normalised log2 precursor intensities\") +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nharmonizing input:\n  removing 12 sampleMap rows not in names(experiments)\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](cptac_files/figure-html/assess_normalisation-1.png){width=672}\n:::\n:::\n\n\n## Summarization to protein level\n\nHere, we summarise the peptide-level data into protein intensities using\n`aggregateFeatures()`, which streamlines summarisation. It requires the name\nof a `rowData` column to group the peptides into proteins (or\nprotein groups), here `Proteins`. We can provide the summarisation\napproach through the `fun` argument. \nWe use the standard summarisation in aggregateFeatures, which is a\nrobust summarisation method.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- aggregateFeatures(qf,\n    i = \"peptides_norm\", \n    fcol = \"Proteins\", \n    na.rm = TRUE,\n    name = \"proteins\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following messages occurred during aggregation:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nYour quantitative and row data contain missing values. Please read the\nrelevant section(s) in the aggregateFeatures manual page regarding the\neffects of missing values on data aggregation.\n\nOccurred during the aggregation of set(s): peptides\n```\n\n\n:::\n:::\n\n\nNote, that robust summarisation can take a long time for large datasets. \nIn that case we suggest to use `fun = MsCoreUtils::medianPolish, na.rm = TRUE`. \nNote that the optional argument na.rm = TRUE is needed when using `medianPolish` \nbecause the data contains missing values as we did not adopt imputation and \n`medianPolish` by default cannot handle missing values. \n\n# Data exploration and QC\n\nData exploration aims to highlight the main sources of variation in\nthe data prior to data modelling and can pinpoint to outlying or\noff-behaving samples. \n\n## Marginal distribution at precursor and protein level \n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf[, , \"peptides_norm\"] |>\n  longForm(colvars = colnames(colData(qf))) |> \n  data.frame() |> \n  filter(!is.na(value)) |>\n  ggplot() + \n  aes(x = value,\n      colour = condition,\n      group = colname) +\n  geom_density() +\n  theme_minimal() +\n   labs(subtitle = \"Normalised log2 precursor intensities\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nharmonizing input:\n  removing 18 sampleMap rows not in names(experiments)\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](cptac_files/figure-html/qc_normalisation_peptides-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf[, , \"peptides_norm\"] |>\n  longForm(colvars = colnames(colData(qf))) |> \n  data.frame() |> \n  filter(!is.na(value)) |>\n  ggplot() + \n  aes(x = sampleId,\n      y = value,\n      colour = condition,\n      group = colname) +\n  xlab(\"sample\") +\n  geom_boxplot() +\n  theme_minimal() +\n   labs(subtitle = \"Normalised log2 precursor intensities\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nharmonizing input:\n  removing 18 sampleMap rows not in names(experiments)\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](cptac_files/figure-html/qc_normalisation_peptides_boxplot-1.png){width=672}\n:::\n:::\n\n\nWe do the same for the protein-level values. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf[, , \"proteins\"] |>\n  longForm(colvars = colnames(colData(qf))) |> \n  data.frame() |> \n  filter(!is.na(value)) |>\n  ggplot() + \n  aes(x = value,\n      colour = condition,\n      group = colname) +\n  geom_density() +\n  theme_minimal() +\n   labs(subtitle = \"Normalised log2 protein intensities\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nharmonizing input:\n  removing 18 sampleMap rows not in names(experiments)\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](cptac_files/figure-html/qc_normalisation_proteins-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf[, , \"proteins\"] |>\n  longForm(colvars = colnames(colData(qf))) |> \n  data.frame() |> \n  filter(!is.na(value)) |>\n  ggplot() + \n  aes(x = sampleId,\n      y = value,\n      colour = condition,\n      group = colname) +\n  xlab(\"sample\") +\n  geom_boxplot() +\n  theme_minimal() +\n   labs(subtitle = \"Normalised log2 protein intensities\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nharmonizing input:\n  removing 18 sampleMap rows not in names(experiments)\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](cptac_files/figure-html/qc_normalisation_proteins_boxplot-1.png){width=672}\n:::\n:::\n\n\n## Identifications per sample \n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf[,,\"peptides_norm\"] |> \n  longForm(colvars = colnames(colData(qf)), \n           rowvars= c(\"Sequence\", \n                      \"Proteins\")) |>\n  data.frame() |>\n  filter(!is.na(value)) |>\n  group_by(condition, sampleId) |>\n  summarise(Precursors = length(unique(Sequence)),\n            `Protein Groups` = length(unique(Proteins))) |> \n  pivot_longer(-(1:2),\n               names_to = \"Feature\",\n               values_to = \"IDs\") |> \n  ggplot(aes(x = sampleId, y = IDs, fill = condition)) +\n  geom_col() +\n  #scale_fill_observable() +\n  facet_wrap(~Feature,\n             scales = \"free_y\") +\n  labs(title = \"Peptide and protein group identifications per sample\",\n       x = \"Sample\",\n       y = \"Identifications\") +\n  theme_bw() + \n  theme(axis.text.x = element_text(angle = 90))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nharmonizing input:\n  removing 18 sampleMap rows not in names(experiments)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has regrouped the output.\nℹ Summaries were computed grouped by condition and sampleId.\nℹ Output is grouped by condition.\nℹ Use `summarise(.groups = \"drop_last\")` to silence this message.\nℹ Use `summarise(.by = c(condition, sampleId))` for per-operation grouping\n  (`?dplyr::dplyr_by`) instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](cptac_files/figure-html/qc_identifications-1.png){width=672}\n:::\n:::\n\n\n## Dimensionality reduction plot \n\nA common approach for data exploration is to\nperform dimension reduction, such as Multi Dimensional Scaling (MDS).\nWe will first extract the set to explore along the sample annotations\n(used for plot colouring).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngetWithColData(qf, \"proteins\") |> \n  as(\"SingleCellExperiment\") |> \n  runMDS(exprs_values = 1) |> \n  plotMDS(colour_by = \"condition\", shape_by = \"rep\", point_size = 3)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: 'experiments' dropped; see 'drops()'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](cptac_files/figure-html/qc_mds_proteins-1.png){width=672}\n:::\n:::\n\n\n\nThis plot reveals interesting information. First, we see that the\nsamples are nicely separated according to their spike-in condition.\nThe also seem to line up according to `rep`. \n\n## Correlation matrix\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorMat <- qf[[\"proteins\"]] |> \n  assay() |>\n  cor(method = \"spearman\", use = \"pairwise.complete.obs\") \n \ncolnames(corMat) <- qf$sampleId\nrownames(corMat) <- qf$sampleId\ncorMat |> \n  ggcorrplot::ggcorrplot() +\n  scale_fill_viridis_c() +\n  labs(title = \"Correlation matrix\",\n       fill = \"Correlation\") +\n  theme(axis.text.x = element_text(angle = 90))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: `aes_string()` was deprecated in ggplot2 3.0.0.\nℹ Please use tidy evaluation idioms with `aes()`.\nℹ See also `vignette(\"ggplot2-in-packages\")` for more information.\nℹ The deprecated feature was likely used in the ggcorrplot package.\n  Please report the issue at <https://github.com/kassambara/ggcorrplot/issues>.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nScale for fill is already present.\nAdding another scale for fill, which will replace the existing scale.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](cptac_files/figure-html/qc_correlation_proteins-1.png){width=672}\n:::\n:::\n\n\n\n# Data Modeling (Robust Regression){#sec-modelling}\n\n## Sources of variation \n\nFor this experiment, we can only model a single source of variation: spike-in \nconcentration. All remaining sources of variability, e.g. pipetting errors, \nMS run to run variability, etc will be lumped in the residual variability \n(error term).\n\nSpike-in condition effects: we model the source of variation induced by the \nexperimental treatment of interest as a fixed effect, which we consider \nnon-random, i.e. the treatment effect is assumed to be the same in repeated \nexperiments, but it is unknown and has to be estimated.\n\nWhen modelling a typical label-free experiment at the protein level, the model \nboils down to the following linear model:\n\n$$ y_i = \\mathbf{x}_i^T\\boldsymbol{\\beta} +\\epsilon_i$$\nwith the $\\log_2$-normalised and summarised protein intensities in sample; \n$\\mathbf{x}_i$ a vector with the covariate pattern for the sample encoding the \nintercept, spike-in condition, or other experimental factors;  \n$\\boldsymbol{\\beta}$ the vector of parameters that model the association between \nthe covariates and the outcome; and $\\epsilon_i$ the residuals reflecting \nvariation that is not captured by the fixed effects. \nNote that this allows for a flexible parameterisation of the treatment\nbeyond a single covariate, i.e. including a 1 for the intercept, continuous and \ncategorical variables as well as their interactions. We assume the residuals to \nbe independent and identically distributed (i.i.d) according to a normal \ndistribution with zero mean and constant variance, \ni.e. $\\epsilon_i \\sim N(0, \\sigma^2_\\epsilon)$, that can differ from protein to \nprotein.\n\nIn R, this model is encoded using the following simple formula:\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- ~ condition\n```\n:::\n\n\n## Model Estimation \n\nWe estimate the model with `msqrob()`. The function takes the QFeatures object, \nextracts the quantitative values from the `\"proteins\"` set generated during \nsummarisation, and fits a simple linear model with `condition` as covariate, \nwhich are automatically retrieved from `colData(qf)`.\nNote, that `msqrob()` can also take a `SummarizedExperiment` of \nprecursor, peptide or protein intensities as its input. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n  qf <- msqrob(\n    qf,  \n    i = \"proteins\",\n    formula = model,\n    robust = TRUE)\n```\n:::\n\n  \n\nWe enable M-estimation (`robust = TRUE`) for improved robustness against outliers.\n\nThe fitting results are available in the `msqrobModels` column of the rowData. More specifically, the modelling output is stored in the `rowData` as a `statModel` object, one model per row (protein). We will see in a later section how to perform statistical inference on the estimated parameters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodels <- rowData(qf[[\"proteins\"]])[[\"msqrobModels\"]]\nmodels[1:3]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`O00762ups|UBE2C_HUMAN_UPS`\nObject of class \"StatModel\"\nThe type is \"rlm\"\nThere number of elements is 7 \n\n$`P00167ups|CYB5_HUMAN_UPS`\nObject of class \"StatModel\"\nThe type is \"rlm\"\nThere number of elements is 7 \n\n$`P00441ups|SODC_HUMAN_UPS`\nObject of class \"StatModel\"\nThe type is \"rlm\"\nThere number of elements is 7 \n```\n\n\n:::\n:::\n\n\n## Statistical inference \n\nWe can now convert the research question “do the spike-in conditions affect the protein intensities?” into a statistical hypothesis.\n\nIn other words, we need to translate this question in a null and alternative hypothesis on a single model parameter or on a linear combination of model parameters, which is also referred to with a contrast.\n\nTo aid defining contrasts, we will visualise the experimental design using the `ExploreModelMatrix` package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvd <- ExploreModelMatrix::VisualizeDesign(\n    sampleData =  colData(qf),\n    designFormula = model,\n    textSizeFitted = 4\n)\nvd$plotlist\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](cptac_files/figure-html/explore_model_matrix-1.png){width=672}\n:::\n:::\n\n\n\nThis plot shows that the average protein $\\log_2$ intensity for conditionA is modelled by `(Intercept)` and that for the `conditionB` group by `(Intercept) + conditionB` .\n \nHence, to assess differential abundance of proteins between the two spike-in conditions, we will have to assess the following null hypothesis:  $\\log_2 FC_{B-A} = (Intercept + conditionB) - Intercept = conditionB = 0$. \n\nBased on this null hypothesis we now generate a contrast matrix. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n(L <- makeContrast(\n  \"conditionB = 0\",\n  parameterNames = colnames(vd$designmatrix)\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            conditionB\n(Intercept)          0\nconditionB           1\n```\n\n\n:::\n:::\n\n\n\nWe can now test our null hypothesis using `hypothesisTest()` which\ntakes the `QFeatures` object with the fitted model and the contrast we\njust built. `msqrob2` automatically applies the hypothesis\ntesting to all features in the assay.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- hypothesisTest(qf, i = \"proteins\", contrast = L)\n```\n:::\n\n\nThe results tables for the contrast are stored in the row data of the \n`proteins` assay in `qf` under the column names of the contrast matrix `L`.\n\nUsers can directly access the results tables via the colData. However, `msqrob2` \nalso provides the `msqrobCollect` function. This function will automatically \nretrieve the results tables for all contrasts in contrast matrix `L` and combine \nthem by default in one  table. This table contains two additional columns: \n`contrast` with the name of the contrast and `feature` with the name of the \nmodelled `feature`, here protein. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ninferences <- \n  msqrobCollect(qf[[\"proteins\"]], L) \nhead(inferences)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                         logFC        se       df         t\nconditionB.O00762ups|UBE2C_HUMAN_UPS  1.544695 0.1464716 5.726358 10.546038\nconditionB.P00167ups|CYB5_HUMAN_UPS         NA        NA 5.000874        NA\nconditionB.P00441ups|SODC_HUMAN_UPS  -0.421279 0.1780461 6.000874 -2.366123\nconditionB.P00709ups|LALBA_HUMAN_UPS  1.333640 0.4673775 6.000874  2.853453\nconditionB.P00915ups|CAH1_HUMAN_UPS   0.000000        NA       NA        NA\nconditionB.P00918ups|CAH2_HUMAN_UPS   1.477407 0.1891851 7.000874  7.809320\n                                             pval     adjPval   contrast\nconditionB.O00762ups|UBE2C_HUMAN_UPS 5.769185e-05 0.005750616 conditionB\nconditionB.P00167ups|CYB5_HUMAN_UPS            NA          NA conditionB\nconditionB.P00441ups|SODC_HUMAN_UPS  5.580925e-02 0.910029883 conditionB\nconditionB.P00709ups|LALBA_HUMAN_UPS 2.904513e-02 0.744439354 conditionB\nconditionB.P00915ups|CAH1_HUMAN_UPS            NA          NA conditionB\nconditionB.P00918ups|CAH2_HUMAN_UPS  1.062242e-04 0.009571350 conditionB\n                                                       feature\nconditionB.O00762ups|UBE2C_HUMAN_UPS O00762ups|UBE2C_HUMAN_UPS\nconditionB.P00167ups|CYB5_HUMAN_UPS   P00167ups|CYB5_HUMAN_UPS\nconditionB.P00441ups|SODC_HUMAN_UPS   P00441ups|SODC_HUMAN_UPS\nconditionB.P00709ups|LALBA_HUMAN_UPS P00709ups|LALBA_HUMAN_UPS\nconditionB.P00915ups|CAH1_HUMAN_UPS   P00915ups|CAH1_HUMAN_UPS\nconditionB.P00918ups|CAH2_HUMAN_UPS   P00918ups|CAH2_HUMAN_UPS\n```\n\n\n:::\n:::\n\n\n\n### Results table for significant proteins\n\nWe will return a table of proteins for which the contrast is significant at the 5% FDR level. \n\n1. We set the significance level \n3. We filter the significant results for the contrast from the table\n4. We print the table \n\n\n```{.r .cell-code}\nalpha <- 0.05 #1.\nsigList <- inferences |> \n    filter(adjPval < alpha) #3.\nkable(sigList) |>\n      kable_styling(full_width = FALSE) |>\n      scroll_box(height = \"250px\") #4.\n```\n\n`````{=html}\n<div style=\"border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:250px; \"><table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;\">  </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> logFC </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> se </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> df </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> t </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> pval </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> adjPval </th>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;\"> contrast </th>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;\"> feature </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.O00762ups&amp;#124;UBE2C_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.544695 </td>\n   <td style=\"text-align:right;\"> 0.1464716 </td>\n   <td style=\"text-align:right;\"> 5.726358 </td>\n   <td style=\"text-align:right;\"> 10.546038 </td>\n   <td style=\"text-align:right;\"> 0.0000577 </td>\n   <td style=\"text-align:right;\"> 0.0057506 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> O00762ups&amp;#124;UBE2C_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P00918ups&amp;#124;CAH2_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.477407 </td>\n   <td style=\"text-align:right;\"> 0.1891851 </td>\n   <td style=\"text-align:right;\"> 7.000874 </td>\n   <td style=\"text-align:right;\"> 7.809320 </td>\n   <td style=\"text-align:right;\"> 0.0001062 </td>\n   <td style=\"text-align:right;\"> 0.0095713 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P00918ups&amp;#124;CAH2_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P01031ups&amp;#124;CO5_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.767896 </td>\n   <td style=\"text-align:right;\"> 0.1930014 </td>\n   <td style=\"text-align:right;\"> 5.463533 </td>\n   <td style=\"text-align:right;\"> 9.160019 </td>\n   <td style=\"text-align:right;\"> 0.0001614 </td>\n   <td style=\"text-align:right;\"> 0.0118909 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P01031ups&amp;#124;CO5_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P01127ups&amp;#124;PDGFB_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.481764 </td>\n   <td style=\"text-align:right;\"> 0.1687895 </td>\n   <td style=\"text-align:right;\"> 6.818259 </td>\n   <td style=\"text-align:right;\"> 8.778764 </td>\n   <td style=\"text-align:right;\"> 0.0000585 </td>\n   <td style=\"text-align:right;\"> 0.0057506 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P01127ups&amp;#124;PDGFB_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P01344ups&amp;#124;IGF2_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.489747 </td>\n   <td style=\"text-align:right;\"> 0.1250054 </td>\n   <td style=\"text-align:right;\"> 6.000874 </td>\n   <td style=\"text-align:right;\"> 11.917465 </td>\n   <td style=\"text-align:right;\"> 0.0000211 </td>\n   <td style=\"text-align:right;\"> 0.0031115 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P01344ups&amp;#124;IGF2_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P01375ups&amp;#124;TNFA_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.866765 </td>\n   <td style=\"text-align:right;\"> 0.2350145 </td>\n   <td style=\"text-align:right;\"> 6.000874 </td>\n   <td style=\"text-align:right;\"> 7.943191 </td>\n   <td style=\"text-align:right;\"> 0.0002115 </td>\n   <td style=\"text-align:right;\"> 0.0146690 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P01375ups&amp;#124;TNFA_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P02144ups&amp;#124;MYG_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.390209 </td>\n   <td style=\"text-align:right;\"> 0.2214167 </td>\n   <td style=\"text-align:right;\"> 6.970553 </td>\n   <td style=\"text-align:right;\"> 6.278698 </td>\n   <td style=\"text-align:right;\"> 0.0004196 </td>\n   <td style=\"text-align:right;\"> 0.0274861 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P02144ups&amp;#124;MYG_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P02787ups&amp;#124;TRFE_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.490130 </td>\n   <td style=\"text-align:right;\"> 0.1488114 </td>\n   <td style=\"text-align:right;\"> 6.578795 </td>\n   <td style=\"text-align:right;\"> 10.013545 </td>\n   <td style=\"text-align:right;\"> 0.0000320 </td>\n   <td style=\"text-align:right;\"> 0.0041878 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P02787ups&amp;#124;TRFE_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P06732ups&amp;#124;KCRM_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.635848 </td>\n   <td style=\"text-align:right;\"> 0.1366995 </td>\n   <td style=\"text-align:right;\"> 7.000874 </td>\n   <td style=\"text-align:right;\"> 11.966742 </td>\n   <td style=\"text-align:right;\"> 0.0000065 </td>\n   <td style=\"text-align:right;\"> 0.0019071 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P06732ups&amp;#124;KCRM_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P07339ups&amp;#124;CATD_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.929497 </td>\n   <td style=\"text-align:right;\"> 0.1809218 </td>\n   <td style=\"text-align:right;\"> 6.000874 </td>\n   <td style=\"text-align:right;\"> 10.664812 </td>\n   <td style=\"text-align:right;\"> 0.0000400 </td>\n   <td style=\"text-align:right;\"> 0.0047210 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P07339ups&amp;#124;CATD_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P08311ups&amp;#124;CATG_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.561305 </td>\n   <td style=\"text-align:right;\"> 0.1045255 </td>\n   <td style=\"text-align:right;\"> 7.000874 </td>\n   <td style=\"text-align:right;\"> 14.937069 </td>\n   <td style=\"text-align:right;\"> 0.0000014 </td>\n   <td style=\"text-align:right;\"> 0.0005676 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P08311ups&amp;#124;CATG_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P09211ups&amp;#124;GSTP1_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.197007 </td>\n   <td style=\"text-align:right;\"> 0.1773925 </td>\n   <td style=\"text-align:right;\"> 5.861064 </td>\n   <td style=\"text-align:right;\"> 6.747789 </td>\n   <td style=\"text-align:right;\"> 0.0005697 </td>\n   <td style=\"text-align:right;\"> 0.0335809 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P09211ups&amp;#124;GSTP1_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P10636-8ups&amp;#124;TAU_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.282407 </td>\n   <td style=\"text-align:right;\"> 0.1153671 </td>\n   <td style=\"text-align:right;\"> 7.000874 </td>\n   <td style=\"text-align:right;\"> 11.115878 </td>\n   <td style=\"text-align:right;\"> 0.0000106 </td>\n   <td style=\"text-align:right;\"> 0.0019071 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P10636-8ups&amp;#124;TAU_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P12081ups&amp;#124;SYHC_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.439463 </td>\n   <td style=\"text-align:right;\"> 0.1714347 </td>\n   <td style=\"text-align:right;\"> 6.000874 </td>\n   <td style=\"text-align:right;\"> 8.396564 </td>\n   <td style=\"text-align:right;\"> 0.0001553 </td>\n   <td style=\"text-align:right;\"> 0.0118909 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P12081ups&amp;#124;SYHC_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P51965ups&amp;#124;UB2E1_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.664890 </td>\n   <td style=\"text-align:right;\"> 0.1512672 </td>\n   <td style=\"text-align:right;\"> 7.000874 </td>\n   <td style=\"text-align:right;\"> 11.006286 </td>\n   <td style=\"text-align:right;\"> 0.0000113 </td>\n   <td style=\"text-align:right;\"> 0.0019071 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P51965ups&amp;#124;UB2E1_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P61769ups&amp;#124;B2MG_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 2.012769 </td>\n   <td style=\"text-align:right;\"> 0.3340379 </td>\n   <td style=\"text-align:right;\"> 6.965852 </td>\n   <td style=\"text-align:right;\"> 6.025572 </td>\n   <td style=\"text-align:right;\"> 0.0005386 </td>\n   <td style=\"text-align:right;\"> 0.0334228 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P61769ups&amp;#124;B2MG_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P63165ups&amp;#124;SUMO1_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.062479 </td>\n   <td style=\"text-align:right;\"> 0.1375085 </td>\n   <td style=\"text-align:right;\"> 7.000874 </td>\n   <td style=\"text-align:right;\"> 7.726642 </td>\n   <td style=\"text-align:right;\"> 0.0001137 </td>\n   <td style=\"text-align:right;\"> 0.0095713 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P63165ups&amp;#124;SUMO1_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P63279ups&amp;#124;UBC9_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.822523 </td>\n   <td style=\"text-align:right;\"> 0.1165455 </td>\n   <td style=\"text-align:right;\"> 7.000874 </td>\n   <td style=\"text-align:right;\"> 15.637873 </td>\n   <td style=\"text-align:right;\"> 0.0000011 </td>\n   <td style=\"text-align:right;\"> 0.0005676 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P63279ups&amp;#124;UBC9_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.P99999ups&amp;#124;CYC_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 2.061623 </td>\n   <td style=\"text-align:right;\"> 0.1372066 </td>\n   <td style=\"text-align:right;\"> 7.000874 </td>\n   <td style=\"text-align:right;\"> 15.025690 </td>\n   <td style=\"text-align:right;\"> 0.0000014 </td>\n   <td style=\"text-align:right;\"> 0.0005676 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> P99999ups&amp;#124;CYC_HUMAN_UPS </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> conditionB.Q06830ups&amp;#124;PRDX1_HUMAN_UPS </td>\n   <td style=\"text-align:right;\"> 1.582654 </td>\n   <td style=\"text-align:right;\"> 0.1418741 </td>\n   <td style=\"text-align:right;\"> 7.000874 </td>\n   <td style=\"text-align:right;\"> 11.155343 </td>\n   <td style=\"text-align:right;\"> 0.0000104 </td>\n   <td style=\"text-align:right;\"> 0.0019071 </td>\n   <td style=\"text-align:left;\"> conditionB </td>\n   <td style=\"text-align:left;\"> Q06830ups&amp;#124;PRDX1_HUMAN_UPS </td>\n  </tr>\n</tbody>\n</table></div>\n\n`````\n\n\n### Volcanoplots \n\nA volcano plot is a common visualisation that provides an overview of\nthe hypothesis testing results, plotting the $-\\log_{10}$ p-value^[Note, \nthat upon this transformation a value of 1 represents a p-value of 0.1, 2 \na p-value of 0.01, 3 a p-value of 0.001, etc.] as a function of\nthe estimated log fold change. Volcano plots can be used to highlight\nthe most interesting proteins that have large fold changes and/or are\nhighly significant. We can use the table above directly to build a\nvolcano plot using `ggplot2` functionality. We also highlight which\nproteins are UPS standards, known to be differentially abundant by\nexperimental design.\n\nExperienced users can make the plot themselves. However, in msqrob2 we also \nprovide the plotVolcano function that generates volcanoplots based on `msqrob2`\ninference tables generated with the `hypothesisTest` function. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninferences |> \n  plotVolcano()\n```\n\n::: {.cell-output-display}\n![](cptac_files/figure-html/volcanoplot-1.png){width=672}\n:::\n:::\n\n\n### Heatmaps\n\nWe construct heatmaps for the significant proteins for each contrast. \n\n1. We get the names of the significant features.\n2. We extract the quant data for the significant features and scale it. \n3. We extract annotation\n4. We make the heatmap using the quants data. We do not cluster columns (samples) to keep them together according to the design.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsig <- sigList |> pull(feature) #1.\n\n\nquants <- assay(qf,\"proteins\")[sig,] |> \n                     t() |> \n                     scale() |>\n                     t() #2.\n \ncolnames(quants) <- qf$sampleId #3.\nannotations <- columnAnnotation(condition = qf$condition) #3.\n\nset.seed(1234) ## annotation colours are randomly generated by default\nHeatmap(\n  quants,\n  name = \"log2 intensity\",\n  top_annotation = annotations\n  )  #4.\n```\n\n::: {.cell-output-display}\n![](cptac_files/figure-html/heatmap-1.png){width=672}\n:::\n:::\n\n\nNote, that 20 DA proteins are returned and that they are all UPS proteins! \n\nA typical workflow for the analysis of a proteomics experiment will end here. \n\n\n\n# References\n\nNote, that more examples can be found in our [msqrob2 book](https://statomics.github.io/msqrob2book).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.6.1 (2026-06-24)\nPlatform: aarch64-apple-darwin23\nRunning under: macOS Tahoe 26.1\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \nLAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n\nlocale:\n[1] nl_BE.UTF-8/nl_BE.UTF-8/nl_BE.UTF-8/C/nl_BE.UTF-8/nl_BE.UTF-8\n\ntime zone: Europe/Brussels\ntzcode source: internal\n\nattached base packages:\n[1] grid      stats4    stats     graphics  grDevices utils     datasets \n[8] methods   base     \n\nother attached packages:\n [1] scater_1.40.1               scuttle_1.22.0             \n [3] SingleCellExperiment_1.34.0 ComplexHeatmap_2.28.0      \n [5] kableExtra_1.4.0            ExploreModelMatrix_1.24.0  \n [7] stringr_1.6.0               msqrob2_1.21.1             \n [9] ggplot2_4.0.3               tidyr_1.3.2                \n[11] dplyr_1.2.1                 QFeatures_1.22.0           \n[13] MultiAssayExperiment_1.38.0 SummarizedExperiment_1.42.0\n[15] Biobase_2.72.0              GenomicRanges_1.64.0       \n[17] Seqinfo_1.2.0               IRanges_2.46.0             \n[19] S4Vectors_0.50.1            BiocGenerics_0.58.1        \n[21] generics_0.1.4              MatrixGenerics_1.24.0      \n[23] matrixStats_1.5.0          \n\nloaded via a namespace (and not attached):\n  [1] RColorBrewer_1.1-3      rstudioapi_0.19.0       jsonlite_2.0.0         \n  [4] shape_1.4.6.1           magrittr_2.0.5          magick_2.9.1           \n  [7] estimability_2.0.0      ggbeeswarm_0.7.3        farver_2.1.2           \n [10] nloptr_2.2.1            rmarkdown_2.31          GlobalOptions_0.1.4    \n [13] vctrs_0.7.3             Cairo_1.7-0             minqa_1.2.8            \n [16] BiocBaseUtils_1.14.2    htmltools_0.5.9         S4Arrays_1.12.0        \n [19] BiocNeighbors_2.6.0     SparseArray_1.12.2      htmlwidgets_1.6.4      \n [22] plyr_1.8.9              igraph_2.3.3            mime_0.13              \n [25] lifecycle_1.0.5         iterators_1.0.14        pkgconfig_2.0.3        \n [28] rsvd_1.0.5              Matrix_1.7-5            R6_2.6.1               \n [31] fastmap_1.2.0           rbibutils_2.4.1         shiny_1.14.0           \n [34] clue_0.3-68             digest_0.6.39           colorspace_2.1-2       \n [37] irlba_2.3.7             textshaping_1.0.5       beachmat_2.28.0        \n [40] labeling_0.4.3          abind_1.4-8             compiler_4.6.1         \n [43] withr_3.0.3             doParallel_1.0.17       S7_0.2.2               \n [46] ggcorrplot_0.1.4.1      BiocParallel_1.46.0     viridis_0.6.5          \n [49] MASS_7.3-65             DelayedArray_0.38.2     rjson_0.2.23           \n [52] tools_4.6.1             vipor_0.4.7             otel_0.2.0             \n [55] beeswarm_0.4.0          httpuv_1.6.17           glue_1.8.1             \n [58] nlme_3.1-169            promises_1.5.0          cluster_2.1.8.2        \n [61] reshape2_1.4.5          gtable_0.3.6            data.table_1.18.4      \n [64] BiocSingular_1.28.0     ScaledMatrix_1.20.0     xml2_1.6.0             \n [67] XVector_0.52.0          ggrepel_0.9.8           foreach_1.5.2          \n [70] pillar_1.11.1           limma_3.68.4            later_1.4.8            \n [73] rintrojs_0.3.4          circlize_0.4.18         splines_4.6.1          \n [76] lattice_0.22-9          tidyselect_1.2.1        knitr_1.51             \n [79] reformulas_0.4.4        gridExtra_2.3.1         ProtGenerics_1.44.0    \n [82] svglite_2.2.2           xfun_0.59               shinydashboard_0.7.3   \n [85] statmod_1.5.2           DT_0.34.0               stringi_1.8.7          \n [88] lazyeval_0.2.3          yaml_2.3.12             boot_1.3-32            \n [91] evaluate_1.0.5          codetools_0.2-20        MsCoreUtils_1.24.0     \n [94] tibble_3.3.1            cli_3.6.6               xtable_1.8-8           \n [97] systemfonts_1.3.2       Rdpack_2.6.6            Rcpp_1.1.1-1.1         \n[100] png_0.1-9               parallel_4.6.1          assertthat_0.2.1       \n[103] AnnotationFilter_1.36.0 lme4_2.0-1              viridisLite_0.4.3      \n[106] scales_1.4.0            purrr_1.2.2             crayon_1.5.3           \n[109] GetoptLong_1.1.1        rlang_1.2.0             cowplot_1.2.0          \n[112] shinyjs_2.1.1          \n```\n\n\n:::\n:::\n\n\n\n",
    "supporting": [
      "cptac_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}