{
  "hash": "cc3b116f8c6cbca558b0ed4b46d2c4b9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Basics of Statistical Inference and Some Experimental Design Concepts\nformat:\n  html: default\n  pdf: default\n---\n\n# Outline {-}\n\n\n::: {.cell}\n\n:::\n\n\n- Francisella tularensis Example\n- Hypothesis testing\n- Multiple testing\n- Moderated statistics\n- Experimental design\n\n\nNote, that this dataset has been acquired with DDA (data dependent acquisition).\nIt was searched with MaxQuant. \nThe analysis starts from the peptides.txt file, which is a table in the output directory of MaxQuant with the data summarized at the peptide-level. \n\nThe preprocessing steps are slightly different. \nThe modeling concepts, however, are also applicable to DIA data. \n\n---\n\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/1mhg3BCuEm8\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\n\n# Francisella tularensis experiment\n\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/TW5rk1y7aOc\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/francisella.jpg){width=50%}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/tularemia_lesion.jpg){width=350}\n:::\n:::\n\n\n- Pathogen: causes tularemia\n- Metabolic adaptation key for intracellular life cycle of pathogenic microorganisms. \n- Upon entry into host cells quick phagosomal escape and active multiplication in cytosolic compartment.\n- Francisella is auxotrophic for several amino acids, including arginine.\n- Inactivation of arginine transporter delayed bacterial phagosomal escape and intracellular multiplication. \n- Experiment to assess difference in proteome using 3 WT vs 3 ArgP KO mutants\n\n\n## Import the data in R \n\n<details><summary> Click to see code </summary><p>\n1. Load libraries \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(limma)\nlibrary(QFeatures)\nlibrary(msqrob2)\nlibrary(plotly)\nlibrary(ggplot2)\n```\n:::\n\n\n2. We use a peptides.txt file from MS-data quantified with maxquant that \ncontains MS1 intensities summarized at the peptide level. \n\n::: {.cell}\n\n```{.r .cell-code}\npeptidesFile <- \"https://raw.githubusercontent.com/statOmics/PDA22GTPB/data/quantification/francisella/peptides.txt\"\n```\n:::\n\n\n3. Maxquant stores the intensity data for the different samples in columns that start with Intensity. We can retrieve the column names with the intensity data with the code below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\necols <- grep(\"Intensity\\\\.\", names(read.delim(peptidesFile)))\n```\n:::\n\n\n4. Read the data and store it in  QFeatures object \n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- readQFeatures(\n  assayData = read.delim(peptidesFile),\n  fnames = 1,\n  quantCols =  ecols,\n  name = \"peptideRaw\")\n```\n:::\n\n\n5. Update data with information on design\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolData(qf)$genotype <- qf[[1]] |> \n  colnames() |> \n  substr(12,13) |>\n  as.factor() |> \n  relevel(\"WT\")\ncolData(qf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDataFrame with 6 rows and 1 column\n                         genotype\n                         <factor>\nIntensity.1WT_20_2h_n3_3       WT\nIntensity.1WT_20_2h_n4_3       WT\nIntensity.1WT_20_2h_n5_3       WT\nIntensity.3D8_20_2h_n3_3       D8\nIntensity.3D8_20_2h_n4_3       D8\nIntensity.3D8_20_2h_n5_3       D8\n```\n\n\n:::\n:::\n\n\n</p></details>\n\n## Preprocessing\n\n<details><summary> Click to see code to log-transfrom the data </summary><p>\n\n1. Log transform\n\n  - peptides with zero intensities are missing peptides and should be represented\nwith a `NA` value rather than `0`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- zeroIsNA(qf, \"peptideRaw\") # convert 0 to NA\n```\n:::\n\n\n  - Logtransform data with base 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- logTransform(qf, base = 2, i = \"peptideRaw\", name = \"peptides_log\")\n```\n:::\n\n\n2. Filtering\n\nOnly use proteotypic proteins\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- filterFeatures(qf, ~ !grepl(pattern = \";\", Proteins))\n```\n:::\n\n\n  - Remove reverse sequences (decoys) and contaminants. Note that this is indicated by the column names Reverse and depending on the version of maxQuant with Potential.contaminants or Contaminants.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- filterFeatures(qf,~Reverse != \"+\")\nqf <- filterFeatures(qf,~ Contaminant != \"+\")\n```\n:::\n\n\n- We keep peptides that were observed at least 4 times out of the $n\n= 6$ samples, so that we can estimate the peptide characteristics. \n\nWe tolerate the following proportion of NAs:\n$\\text{pNA} = \\frac{(n - 4)}{n} = 0.33$, so we keep peptides that\nare observed in at least 66.7% of the samples. This is an arbitrary\nvalue that may need to be adjusted depending on the experiment and the\ndata set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnObs <- 4\nn <- ncol(qf[[\"peptides_log\"]])\n\n(qf <- filterNA(qf, i = \"peptides_log\", pNA = (n - nObs) / n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAn instance of class QFeatures (type: bulk) with 2 sets:\n\n [1] peptideRaw: SummarizedExperiment with 10461 rows and 6 columns \n [2] peptides_log: SummarizedExperiment with 5052 rows and 6 columns \n```\n\n\n:::\n:::\n\n\n\nWe keep 5052 peptides upon filtering.\n\n3. Normalization by median centering\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <-  sweep( #4. Subtract log2 norm factor column-by-column (MARGIN = 2)\n  qf,\n  MARGIN = 2, \n  STATS = nfLogMedianOfRatios(qf, i=\"peptides_log\"), #1.\n  i = \"peptides_log\",\n  name = \"peptides_norm\"\n)\n```\n:::\n\n\n\n4. Summarization. We use maxLFQ from the iq package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- aggregateFeatures(qf,\n    i = \"peptides_norm\", \n    fcol = \"Proteins\", \n    name = \"proteins\",\n    fun = function(X) iq::maxLFQ(X)$estimate\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n:::\n\n\n\nPlot of preprocessed data \n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf[, , \"peptides_norm\"] |> #1.\n  longForm(colvars = c( \"genotype\")) |>  #2. \n  data.frame() |> \n  filter(!is.na(value)) |>\n  ggplot() + #3.\n  aes(x = value,\n      colour = genotype,\n      group = colname) +\n  geom_density() +\n  theme_minimal() +\n  ggtitle(\"Peptide-level\")\n```\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n\n```{.r .cell-code}\nqf[, , \"proteins\"] |> #1.\n  longForm(colvars = c( \"genotype\")) |>  #2. \n  data.frame() |> \n  filter(!is.na(value)) |>\n  ggplot() + #3.\n  aes(x = value,\n      colour = genotype,\n      group = colname) +\n  geom_density() +\n  theme_minimal() +\n    ggtitle(\"Protein-level\")\n```\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-16-2.png){width=672}\n:::\n:::\n\n</p></details>\n\n## Summarized data structure\n\n### Design\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf |> \n  colData() |> \n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|                         |genotype |\n|:------------------------|:--------|\n|Intensity.1WT_20_2h_n3_3 |WT       |\n|Intensity.1WT_20_2h_n4_3 |WT       |\n|Intensity.1WT_20_2h_n5_3 |WT       |\n|Intensity.3D8_20_2h_n3_3 |D8       |\n|Intensity.3D8_20_2h_n4_3 |D8       |\n|Intensity.3D8_20_2h_n5_3 |D8       |\n\n\n:::\n:::\n\n\n- WT vs KO \n- 3 vs 3 repeats \n\n### Summarized intensity matrix\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf[[\"proteins\"]] |> \n  assay() |> \n  head() |> \n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|             | Intensity.1WT_20_2h_n3_3| Intensity.1WT_20_2h_n4_3| Intensity.1WT_20_2h_n5_3| Intensity.3D8_20_2h_n3_3| Intensity.3D8_20_2h_n4_3| Intensity.3D8_20_2h_n5_3|\n|:------------|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|\n|WP_003013731 |                 25.91971|                 26.03992|                 26.27133|                 25.93598|                 26.19855|                 26.22295|\n|WP_003013909 |                 25.87033|                 25.65042|                 25.74652|                 26.07970|                 25.90919|                 26.03624|\n|WP_003014068 |                 26.79067|                 26.76619|                 27.08102|                 26.62292|                 26.80336|                 26.77253|\n|WP_003014122 |                 25.30922|                 24.96019|                 25.18033|                 24.92020|                 24.80622|                 24.86137|\n|WP_003014123 |                 25.86714|                 25.66709|                 25.77431|                 25.70902|                 25.71849|                 25.53778|\n|WP_003014302 |                 27.85088|                 27.93109|                 27.87884|                 28.01439|                 28.02191|                 28.05122|\n\n\n:::\n:::\n\n\n- 1020 proteins \n\n## Hypothesis testing: a single protein \n\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/myP6SUlSwsM\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n### T-test\n\n\n$$\n \\log_2 \\text{FC} = \\bar{y}_{p1}-\\bar{y}_{p2}\n$$\n\n$$\nT_g=\\frac{\\log_2 \\widehat{\\text{FC}}}{\\text{se}_{\\log_2 \\widehat{\\text{FC}}}}\n$$\n\n$$\nT_g=\\frac{\\widehat{\\text{signal}}}{\\widehat{\\text{Noise}}}\n$$\n\nIf we can assume equal variance in both treatment groups:\n\n$$\n\\text{se}_{\\log_2 \\text{FC}}=\\text{SD}\\sqrt{\\frac{1}{n_1}+\\frac{1}{n_2}}\n$$\n\n### Linear model \n\n$$\n\\begin{array}{lcl}\ny_i &=& \\beta_0 + \\beta_{D8}x_{i,D8} + \\epsilon_i\\\\\n\\epsilon_i &\\sim& N(0,\\sigma^2)\\\\\n\\end{array}\n$$\n- $x_{i,D8}$ is dummy variable\n\n$$\n\\begin{array}{lcl}\nx_{i,D8} &=& 0 \\text{ (WT)}\\\\\nx_{i,D8} &=& 1 \\text{ (D8)}\n\\end{array}\n$$\n- $\\log_2$ FC?\n\n$$\n\\begin{array}{lcl}\n\\hat \\mu_{WT} &=& \\hat\\beta_0 \\\\  \n\\hat \\mu_{D8} &=& \\hat\\beta_0 + \\hat{\\beta}_{D8}\\\\\n\\log_2 \\widehat{\\text{FC}} &=& \\hat{\\beta}_{D8}\n\\end{array}\n$$\nIn R\n\n```\nlm(intensity ~ genotype, data = WP_003023392)\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWP_003023392 <- data.frame(\n    intensity = assay(qf[[\"proteins\"]][\"WP_003023392\",]) |> c(), \n    genotype = colData(qf)[,1]) \n\nWP_003023392 |> \n  ggplot(aes(x=genotype,y=intensity)) + \n  geom_point() +\n  ggtitle(\"Protein WP_003023392\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n$$\nt=\\frac{\\log_2\\widehat{\\text{FC}}}{\\text{se}_{\\log_2\\widehat{\\text{FC}}}}=\\frac{-1.37}{0.103}=-13.2\n$$\n\n- Is t = -13.2 indicating that\nthere is an effect?\n\n- How likely is it to observe\nt = -13.2 when there is no effect of the argP KO on the protein expression?\n\n### Null hypothesis ($H_0$) and alternative hypothesis ($H_1$)\n\n- With data we can never prove a hypothesis (falsification principle of Popper)\n- With data we can only reject a hypothesis \n\n- In general we start from *alternative hypothesis* $H_1$: we want to show an effect of the KO on a protein\n\n<center>\n$H_1$: On average the protein abundance in WT is different from that in KO\n</center>\n\n- But, we will assess this by falsifying the opposite: \n<center>\n$H_0$: On average the protein abundance in WT is equal to that in KO\n</center>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm1 <- lm(intensity ~ genotype, data = WP_003023392)\nsummary(lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = intensity ~ genotype, data = WP_003023392)\n\nResiduals:\n       1        2        3        4        5        6 \n 0.07266 -0.12677  0.05411  0.03622 -0.15565  0.11943 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 26.10746    0.07308  357.27 3.68e-10 ***\ngenotypeD8  -1.36902    0.10334  -13.25 0.000188 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1266 on 4 degrees of freedom\nMultiple R-squared:  0.9777,\tAdjusted R-squared:  0.9721 \nF-statistic: 175.5 on 1 and 4 DF,  p-value: 0.0001877\n```\n\n\n:::\n:::\n\n\n- How likely is it to observe an equal or more extreme effect than the one observed in the sample when the null hypothesis is true?\n- When we make assumptions about the distribution of our test statistic we can quantify this probability: *p-value*. \nThe p-value will only be calculated correctly if the underlying assumptions hold!\n- When we repeat the experiment, the probability to observe a fold change for this gene that is more extreme than a 2.58 fold ($\\log_2 FC=-1.37$) down or up regulation by random chance (if $H_0$ is true) is 2 out of 10000.  \n- If the p-value is below a significance threshold $\\alpha$ we reject the null hypothesis. *We control the probability of a false positive result at the $\\alpha$-level (type I error)*\n\n- Note, that the p-values are uniform under the null hypothesis, i.e. when $H_0$ is true all p-values are equally likely. \n\n## Multiple hypothesis testing\n\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/cLn-CFyA6ps\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\n\n- Consider testing DA for all $m=1066$ proteins simultaneously\n- What if we assess each individual test at level $\\alpha$?\n$\\rightarrow$ Probability to have a false positive (FP) among all m simultaneous\ntests $>>>  \\alpha= 0.05$\n\n- Indeed for each non DA protein we have a probability of 5% to return a FP.\n- In a typical experiment the majority of the proteins are non DA. \n- So an upper bound of the expected FP is $m \\times \\alpha$ or $1066 \\times 0.05=53$. \n\n$\\rightarrow$ Hence, we are bound to call many false positive proteins each time we run the experiment.\n\n### Multiple testing\n\n#### Family-wise error rate\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/IL_eUSyRDRA\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\nThe family-wise error rate (FWER) addresses the multiple testing issue by no longer controlling the individual type I error for each protein, instead it controls:  \n\n$$\n\\text{FWER} = \\text{P}\\left[FP \\geq 1 \\right]\n$$\n\nThe Bonferroni method is widely used to control the type I error: \n\n- assess each test at $$\\alpha_\\text{adj}=\\frac{\\alpha}{m}$$\n\n \n- or use adjusted p-values and compare them to $\\alpha$: \n$$p_\\text{adj}=\\text{min}\\left(p \\times m,1\\right)$$\n\n\nProblem, the method is very conservative! \n\n#### False discovery rate\n\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/envDqvEwRcc\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\n\n- FDR: Expected proportion of false positives on the total number of positives you return.\n- An FDR of 1% means that on average we expect 1% false positive proteins in the list of proteins that are called significant.\n- Defined by Benjamini and Hochberg in their seminal paper Benjamini, Y. and Hochberg, Y. (1995). \"Controlling the false discovery rate: a practical and powerful approach to multiple testing\". Journal of the Royal Statistical Society Series B, 57 (1): 289–300. \n\nThe **False Discovery Proportion (FDP)** is the fraction of false positives that are returned, i.e. \n\n$$\nFDP = \\frac{FP}{R}\n$$\n\n- However, this quantity cannot be observed because in practice we only know the number of proteins for which we rejected $H_0$, $R$. \n- But, we do not know the number of false positives, $FP$.\n\nTherefore, Benjamini and Hochberg, 1995, defined The **False Discovery Rate (FDR)** as\n$$\n   \\text{FDR} = \\text{E}\\left[\\frac{FP}{R}\\right] =\\text{E}\\left[\\text{FDP}\\right]\n$$\nthe expected FDP. \n\n- Controlling the FDR allows for more discoveries (i.e. longer lists with significant results), while the fraction of false discoveries among the significant results is well controlled on average. As a consequence, more of the true positive hypotheses will be detected.\n\n\n#### Intuition of BH-FDR procedure\n\nConsider $m = 1000$ tests\n\n- Suppose that a researcher rejects all null hypotheses for which $p < 0.01$. \n\n- If we use $p < 0.01$, we expect $0.01 \\times m_0$ tests to return false positives. \n- A conservative estimate of the number of false positives that we can expect can be obtained by considering that the null hypotheses are true for all features, $m_0 = m =  1000$. \n- We then would expect $0.01 \\times 1000 = 10$ false positives ($FP=10$).\n\n- Suppose that the researcher found 200 genes with $p<0.01$ ($R=200$).\n\n- The proportion of false positive results (FDP = false positive proportion) among the list of $R=200$ genes can then be estimated as\n\n$$\n   \\widehat{\\text{FDP}}=\\frac{\\widehat{FP}}{R}=\\frac{10}{200}=\\frac{0.01 \\times 1000}{200} = 0.05.\n$$\n\n\n#### Benjamini and Hochberg (1995) procedure for controlling the FDR at $\\alpha$\n\n1. Let $p_{(1)}\\leq \\ldots \\leq p_{(m)}$ denote the ordered $p$-values.\n\n2. Find the largest integer $k$ so that \n$$\n\\frac{p_{(k)} \\times m}{k} \\leq \\alpha\n$$\n$$\\text{or}$$\n$$\np_{(k)} \\leq k \\times \\alpha/m\n$$\n\n3. If such a $k$ exists, reject the $k$ null hypotheses associated with $p_{(1)}, \\ldots, p_{(k)}$.\nOtherwise none of the null hypotheses is rejected.\n\nThe adjusted $p$-value (also known as the $q$-value in FDR literature):\n $$\n   q_{(i)}=\\tilde{p}_{(i)} = \\min\\left[\\min_{j=i,\\ldots, m}\\left(m p_{(j)}/j\\right), 1 \\right].\n $$\n In the hypothetical example above: $k=200$, $p_{(k)}=0.01$, $m=1000$ and $\\alpha=0.05$.\n\n#### Francisella Example\n\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/B3BmnOLkYg4\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\n<details><summary> Click to see code </summary><p>\n\n::: {.cell}\n\n```{.r .cell-code}\nttestMx <- function(y,group) {\n    test <- try(t.test(y[group],y[!group],var.equal=TRUE),silent=TRUE)\n    if(is(test,\"try-error\")) {\n      return(c(log2FC=NA,se=NA,tstat=NA,p=NA))\n      } else {\n      return(c(log2FC= (test$estimate%*%c(1,-1)),se=test$stderr,tstat=test$statistic,pval=test$p.value))\n      }\n }\n \n res <- apply(\n    assay(qf[[\"proteins\"]]), \n    1, \n    ttestMx,\n    group = colData(qf)$genotype==\"D8\") |> \n  t()\n colnames(res) <- c(\"logFC\",\"se\",\"tstat\",\"pval\")\n res <- res |> \n   as.data.frame() |> \n   na.exclude() |> \n   arrange(pval)\n res$adjPval <- p.adjust(res$pval, \"fdr\")\n alpha <- 0.05\nres$adjAlphaForm <- paste0(1:nrow(res),\" x \",alpha,\"/\",nrow(res))\nres$adjAlpha <- alpha * (1:nrow(res))/nrow(res) \nres$\"pval < adjAlpha\" <- res$pval < res$adjAlpha \nres$\"adjPval < alpha\" <- res$adjPval < alpha \n```\n:::\n\n</p></details>\n\nBelow you can find a results table illustrating the BH-FDR correction. For your reference we also give the Bonferroni adjusted significance level that can be applied to the raw p-values, so that you can also assess how many features we would return when controlling the FWER instead: $\\alpha_\\text{adj}^\\text{Bonferroni} = \\alpha/m = 0.05 / 1020= 5\\times 10^{-5}$\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|             |      logFC|      pval|   adjPval|adjAlphaForm   |  adjAlpha|pval < adjAlpha |adjPval < alpha |\n|:------------|----------:|---------:|---------:|:--------------|---------:|:---------------|:---------------|\n|WP_003034781 |  0.4224142| 0.0000022| 0.0022721|1 x 0.05/1020  | 0.0000490|TRUE            |TRUE            |\n|WP_003040849 | -1.2263612| 0.0000076| 0.0026390|2 x 0.05/1020  | 0.0000980|TRUE            |TRUE            |\n|WP_011733723 | -0.3258931| 0.0000078| 0.0026390|3 x 0.05/1020  | 0.0001471|TRUE            |TRUE            |\n|WP_003041244 |  0.2057070| 0.0000791| 0.0201736|4 x 0.05/1020  | 0.0001961|TRUE            |TRUE            |\n|WP_003038430 | -0.3836478| 0.0001838| 0.0280097|5 x 0.05/1020  | 0.0002451|TRUE            |TRUE            |\n|WP_003023392 | -1.3690155| 0.0001877| 0.0280097|6 x 0.05/1020  | 0.0002941|TRUE            |TRUE            |\n|WP_011733588 | -0.3823744| 0.0001922| 0.0280097|7 x 0.05/1020  | 0.0003431|TRUE            |TRUE            |\n|WP_011733645 |  0.3040827| 0.0002362| 0.0301195|8 x 0.05/1020  | 0.0003922|TRUE            |TRUE            |\n|WP_004339068 |  0.1975424| 0.0006535| 0.0730468|9 x 0.05/1020  | 0.0004412|FALSE           |FALSE           |\n|WP_003018840 | -0.5013825| 0.0007161| 0.0730468|10 x 0.05/1020 | 0.0004902|FALSE           |FALSE           |\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n...\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|             |           |          |          |                 |         |      |      |\n|:------------|----------:|---------:|---------:|:----------------|--------:|:-----|:-----|\n|WP_003022463 | -0.0003682| 0.9989893| 0.9999324|1019 x 0.05/1020 | 0.049951|FALSE |FALSE |\n|WP_003033335 | -0.0000299| 0.9999324| 0.9999324|1020 x 0.05/1020 | 0.050000|FALSE |FALSE |\n\n\n:::\n:::\n\n\n\n\n\n#### Results\n\n<details><summary> Click to see code </summary><p>\n\n::: {.cell}\n\n```{.r .cell-code}\nvolcanoT <- plotVolcano(res) \n```\n:::\n\n</p></details>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvolcanoT\n```\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n## Moderated Statistics\n\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/_Q11LXDy0xU\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\n\nProblems with ordinary t-test\n\n<details><summary> Click to see code </summary><p>\n\n::: {.cell}\n\n```{.r .cell-code}\nproblemPlots <- list() \nproblemPlots[[1]] <- res |> \n  ggplot(aes(x = logFC, y = se, color = adjPval < 0.05)) +\n    geom_point(cex = 2.5) +\n    scale_color_manual(values = alpha(c(\"black\", \"red\"), 0.5)) +\n    theme_minimal() \n\nfor (i in 2:3)\n{\nproblemPlots[[i]] <- colData(qf) |> \n    as.data.frame() |> \n    mutate(intensity = qf[[\"proteins\"]][rownames(res)[i],] |> \n             assay() |> \n             c()) |> \n    ggplot(aes(x=genotype,y=intensity)) +\n    geom_point() + \n    ggtitle(rownames(res)[i]) +\n    ylim(c(24,27)) +\n      theme_minimal() \n}\n```\n:::\n\n</p></details>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproblemPlots\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[2]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-28-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[3]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-28-3.png){width=672}\n:::\n:::\n\n\nA general class of moderated test statistics is given by\n $$\n   T_g^{mod} = \\frac{\\bar{Y}_{g1} - \\bar{Y}_{g2}}{C \\quad \\tilde{S}_g} ,\n $$\n where $\\tilde{S}_g$ is a moderated standard deviation estimate. \n\n- $C$ is a constant depending on the design e.g. $\\sqrt{1/{n_1}+1/n_2}$ for a t-test and of another form for linear models.\n- $\\tilde{S}_g=S_g+S_0$: add small positive constant to denominator of t-statistic. \n- This can be adopted in perseus. \n\n<details><summary> Click to see code </summary><p>\n\n::: {.cell}\n\n```{.r .cell-code}\nsimI<-sapply(res$se/sqrt(1/3+1/3),function(n,mean,sd) rnorm(n,mean,sd),n=6,mean=0) |> t()\nresSim <- apply(\n    simI, \n    1, \n    ttestMx,\n    group = colData(qf)$genotype==\"D8\") |> \n  t() \n colnames(resSim) <- c(\"logFC\",\"se\",\"tstat\",\"pval\")\n resSim <- as.data.frame(resSim)\n tstatSimPlot <- resSim |> \n   ggplot(aes(x=tstat)) +\n     geom_histogram(aes(y=..density.., fill=..count..),bins=30) +\n     stat_function(fun=dt,\n    color=\"red\",\n    args=list(df=4)) + \n   ylim(0,.6) +\n   ggtitle(\"t-statistic\") +\n   theme_minimal()\n\n \n resSim$C <- sqrt(1/3+1/3) \n resSim$sd <- resSim$se/resSim$C \n tstatSimperseus <- resSim |> \n   ggplot(aes(x=logFC/((sd+.1)*C))) +\n     geom_histogram(aes(y=..density.., fill=..count..),bins=30) +\n     stat_function(fun=dt,\n                   color=\"red\",\n                  args=list(df=4)) + \n     ylim(0,.6) +\n    ggtitle(\"perseus\") +\n   theme_minimal()\n```\n:::\n\n\n</p></details>\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n- The choice of $S_0$ in perseus is ad hoc and the t-statistic is no-longer t-distributed. \n- permutation test, but is difficult for more complex designs.\n- Allows for Data Dredging because user can choose $S_0$ \n\n\n### Empirical Bayes \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/limmaShrinkage.png){width=50%}\n:::\n:::\n\n\nFigure courtesy to Rafael Irizarry\n\n$$\n   T_g^{mod} = \\frac{\\bar{Y}_{g1} - \\bar{Y}_{g2}}{C \\quad \\tilde{S}_g} ,\n $$\n\n- **empirical Bayes** theory provides a formal framework for borrowing strength across proteins,\n- Implemented in popular bioconductor packages **limma** and **msqrob2**\n\n$$\n  \\tilde{S}_g=\\sqrt{\\frac{d_gS_g^2+d_0S_0^2}{d_g+d_0}},\n$$\n\n- $S_0^2$: common variance (over all proteins) \n- Moderated t-statistic is t-distributed with $d_0+d_g$ degrees of freedom. \n- Note that the degrees of freedom increase by borrowing strength across proteins!\n\n<details><summary> Click to see the code </summary><p>   \n\n1. We model the protein level expression values using the `msqrob` function.\nBy default `msqrob2` estimates the model parameters using robust regression.\n\nWe will model the data with a different group mean for every genotype. \nThe group is incoded in the variable `genotype` of the colData. \nWe can specify this model by using a formula with the factor `genotype` as its predictor: \n`formula = ~genotype`.\n\nNote, that a formula always starts with a symbol '~'.\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- msqrob(object = qf, i = \"proteins\", formula = ~genotype)\n```\n:::\n\n\n2. Inference \n\nWe first explore the design of the model that we specified using the the package `ExploreModelMatrix` \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ExploreModelMatrix)\nVisualizeDesign(colData(qf),~genotype)$plotlist[[1]]\n```\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\nWe have two model parameters, the (Intercept) and genotypeD8. \nThis results in a model with two group means: \n\n1. For the wild type (WT) the expected value (mean) of the log2 transformed intensity y for a protein will be modelled using \n\n$$\\text{E}[Y\\vert \\text{genotype}=\\text{WT}] = \\text{(Intercept)}$$ \n\n2. For the knockout genotype D8 the expected value (mean) of the log2 transformed intensity y for a protein will be modelled using \n\n$$\\text{E}[Y\\vert \\text{genotype}=\\text{D8}] = \\text{(Intercept)} + \\text{genotypeD8}$$ \n\nThe average log2FC between D8 and WT is thus\n$$\\log_2\\text{FC}_{D8-WT}= \\text{E}[Y\\vert \\text{genotype}=\\text{D8}] - \\text{E}[Y\\vert \\text{genotype}=\\text{WT}] = \\text{genotypeD8}\n$$\n\nHence, assessing the null hypothesis that there is no differential abundance between D8 and WT can be reformulated as\n\n$$H_0:  \\text{genotypeD8}=0$$\nWe can implement a hypothesis test for each protein in msqrob2 using the code below: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nL <- makeContrast(\"genotypeD8 = 0\", parameterNames = c(\"genotypeD8\"))\nqf <- hypothesisTest(object = qf, i = \"proteins\", contrast = L)\n```\n:::\n\n\nWe can show the list with all significant DE proteins at the 5% FDR using \n\n::: {.cell}\n\n```{.r .cell-code}\nmsqrobCollect(qf[[\"proteins\"]],L) |> \n  arrange(pval) |>\n  filter(adjPval<0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                             logFC         se       df          t         pval\ngenotypeD8.WP_003040849 -1.2263612 0.08020151 6.087933 -15.290999 4.358069e-06\ngenotypeD8.WP_003023392 -1.3690155 0.11105902 6.087933 -12.326919 1.560512e-05\ngenotypeD8.WP_003033719 -1.1615474 0.12602389 5.828253  -9.216882 1.087304e-04\ngenotypeD8.WP_003026016 -0.9540456 0.11530658 6.080135  -8.273991 1.573910e-04\ngenotypeD8.WP_003033046 -0.8219170 0.10214460 5.815009  -8.046603 2.307079e-04\ngenotypeD8.WP_003038350  0.8077325 0.10952806 6.087933   7.374663 2.978545e-04\n                            adjPval   contrast      feature\ngenotypeD8.WP_003040849 0.004301414 genotypeD8 WP_003040849\ngenotypeD8.WP_003023392 0.007701128 genotypeD8 WP_003023392\ngenotypeD8.WP_003033719 0.035772317 genotypeD8 WP_003033719\ngenotypeD8.WP_003026016 0.038836240 genotypeD8 WP_003026016\ngenotypeD8.WP_003033046 0.045541744 genotypeD8 WP_003033046\ngenotypeD8.WP_003038350 0.048997070 genotypeD8 WP_003038350\n```\n\n\n:::\n:::\n\n\nWe can also visualise the results using a volcanoplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvolcano <- plotVolcano(\n    rowData(qf[[\"proteins\"]])$genotypeD8) +\n  ggtitle(\"msqrob2\")\n```\n:::\n\n</p></details>\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n- The volcano plot opens up when using the EB variance estimator\n\n-  Borrowing strength to estimate the variance using empirical Bayes solves the issue of returning proteins with a low fold change as significant due to a low variance. \n\n\n### Shrinkage of the  variance and moderated t-statistics\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\n- Small variances are shrunken towards the common variance resulting in large EB variance estimates\n- Large variances are shrunken towards the common variance resulting in smaller EB variance estimates \n- Pooled degrees of freedom of the EB variance estimator are larger because information is borrowed across proteins to estimate the variance\n\n## Plots \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-40-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-40-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-40-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-40-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-40-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-40-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-40-8.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-40-9.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-40-10.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-40-11.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](03-inference_files/figure-html/unnamed-chunk-40-12.png){width=672}\n:::\n:::\n\n\n# Experimental Design\n\n## Random Sampling\n\n- Random sampling is closely related to the concept of the population or the scope of the study.\n\n- Based on a sample of subjects, the researchers want to come to conclusions that hold for\n\n    - all kinds of people\n    - people with hypertension\n\n- Scope of the study should be well specified before the start of the study.\n\n- Representative sample: For the statistical analysis to be valid, it is required that the subjects are selected completely at random from the population to which we want to generalize our conclusions.\n\n- Selecting completely at random from a population implies:\n    - all subjects in the population should have the same probability of being selected in the sample,\n    - the selection of a subject in the sample should be independent from the selection of the other subjects in the sample.\n\n\n## Randomisation \n\n- Make sure that groups are comparable / Avoid systematic differences between groups\n- Randomisation: treatments of interest are attributed at random to the experimental units (subjects, animals, plants, cages, ...)\n\n\n## Control\n\nGood control is necessary\n\n$\\rightarrow$ Placebo controlled double blind experiments     \n$\\rightarrow$ Injection of control animal with blank containing same solvents, etc. \n\n## Replication / Sample size \n\nWithin an experiment: Enables to estimate uncertainty / biological variability\n\n- Replication is essential for quantifying the noise\n\n- Noise: biological and technical in nature\n\nBetween experiments: Any true finding should be reproducible\n\n- Genuine replicates include all sources of variability: technical + biological\n\n- Technical replicates are important if you assess new technologies\n\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/uELgkzDjVRY\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\n\n$$\n \\log_2 \\text{FC} = \\bar{y}_{p1}-\\bar{y}_{p2}\n$$\n\n$$\nT_g=\\frac{\\log_2 \\text{FC}}{\\text{se}_{\\log_2 \\text{FC}}}\n$$\n\n$$\nT_g=\\frac{\\widehat{\\text{signal}}}{\\widehat{\\text{Noise}}}\n$$\n\nIf we can assume equal variance in both treatment groups:\n\n$$\n\\text{se}_{\\log_2 \\text{FC}}=\\text{SD}\\sqrt{\\frac{1}{n_1}+\\frac{1}{n_2}}\n$$\n\n$\\rightarrow$ if number of bio-repeats increases we have a higher power!\n\n- cfr. Study of tamoxifen treated Estrogen Receptor (ER) positive breast cancer patients (tutorial)\n\n## Randomized complete block designs\n\n\n\n$$\\sigma^2= \\sigma^2_{bio}+\\sigma^2_\\text{lab} +\\sigma^2_\\text{extraction} + \\sigma^2_\\text{run} + \\ldots$$\n\n- Biological: fluctuations in protein level between mice, fluctuations in protein level between cells, ...\n- Technical: cage effect, lab effect, week effect, plasma extraction, MS-run, ...\n\n## Nature methods: Points of significance - Blocking \n\n[https://www.nature.com/articles/nmeth.3005.pdf](https://www.nature.com/articles/nmeth.3005.pdf)\n\n\n### Mouse example \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/mouseTcell_RCB_design.png){width=50%}\n:::\n:::\n\nDuguet et al. (2017) MCP 16(8):1416-1432. doi: 10.1074/mcp.m116.062745\n\n- All treatments of interest are present within block!\n- We can estimate the effect of the treatment within block!\n- We can isolate the between block variability from the analysis using linear model:\n$$ \n\\sim \\text{type} + \\text{mouse}\n$$\n- Not possible with perseus!\n\n### Assess the impact of blocking in the tutorial session!\n\n- Completely randomized design with only one cell type per mouse (Treg and Tconv)\n\n$$\\updownarrow$$\n\n- Randomized complete block design assessing Treg and Tconv in each mouse\n\n\n# References",
    "supporting": [
      "03-inference_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}