{
  "hash": "2140e7f4a3a07fe73eccb6bf86588824",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Biostatistics - Basics of experimental design, data processing and differential analysis\"\n---\n\n\n::: {.cell}\n\n:::\n\n# Motivating example (Brunner et al. 2022)\n\n<img src=\"./figs/brunner2022PCA.jpg\" width=\"100%\">\n\nBrunner et al. 2022. Mol Syst Biol. 18(3): e10798. doi: 10.15252/msb.202110798\n\n- Single cell study on 231 HeLa cells with drug induced cell cycle arrest for which over 2500 proteins were measured with MS-SCP. \n\n- Authors report:  \n\n\"The proteomes of the different cell cycle states grouped together in a principal component analysis (PCA) plot\". \n\n\"Our single‐cell data set also highlighted proteins not previously associated with the cell cycle and the G2/M transition\"\n\n## Reanalysis of the results\n\nWe can reproduce the results ([Vanderaa and Gatto 2022](https://uclouvain-cbio.github.io/SCP.replication/articles/brunner2022.html)): \n\n<img src=\"./figs/brunnerPCACellCycle.png\" width=\"100%\">\n\nAnother way to look at the same plot\n\n<img src=\"./figs/brunnerPCABatch.png\" width=\"100%\">\n\n<details><summary> What happened </summary><p>\n\nConfounding between acquisition batch and cell cycle arrest!!\n\nTo consult the statistician after an experiment is finished is often merely to ask him to conduct a post mortem examination. He can perhaps say what the experiment died of. -- Ronald Fisher\n\n</p></details>\n\nThinking about design before your experiment is key!!!!\n\n## Why stats\n\n- Statistics is the science on\n    1. collecting (experimental design),\n    2. exploring (data exploration) and\n    3. learning from data and to generalize what we observe in the sample towards the population while quantifying, controlling and reporting variability and uncertainty (statistical modelling and statistical inference).\n\n\n## Structure of the lecture\n\n1. Understand properties of MS-based proteomics data / Data Processing\n2. Differential Abundance analysis of MS-based proteomics Data / Statistical Modeling & Inference\n3. Some important aspects of experimental design \n\n# Data Processing \n\n## Data Background\n\n### Data acquisition \n\n#### Data Dependent Acquisition \n\n\n::: {.cell}\n::: {.cell-output-display}\n![Overview of an LFQ-based proteomics workflow.](figs/lfq_workflow.png){width=60%}\n:::\n:::\n\n  \n\n- Peptide Characteristics\n  \n  - Modifications\n  - Ionisation Efficiency: huge variability\n  - Identification\n    - Misidentification $\\rightarrow$ outliers\n    - MS$^2$ selection on peptide abundance\n    - Context depending missingness\n    - Non-random missingness\n    - Random missingness\n\n$\\rightarrow$ Unbalanced pepide identifications across samples and messy data\n\n#### Data Independent Acquisition \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Data-independent acquisition.](./figs/dia.png){width=90%}\n:::\n:::\n\n\n- m/z range into sequential windows (e.g., 400–425, 425–450 m/z) \n- MS2 spectra are complex as many peptides mixed\n- Deconvolution of the MS2 signal \n- With dedicated software such as Spectronaut or DIA-NN\n\n    - Identification based on spectral libraries\n    - Library free: FASTA database to predict in silico spectra, retention times, and ion mobilities, which are then used to search the DIA data\n    - Use of decoys sequences to estimate false discovery rate of ID \n    \n- Quantification using MS2 and/or MS1 peaks\n\n### Level of quantification\n\n- MS-based proteomics returns peptides or precursors: pieces of proteins\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/challenges_peptides.png){width=256}\n:::\n:::\n\n\n- Quantification commonly required on the protein level\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/challenges_proteins.png){width=258}\n:::\n:::\n\n\n\n### Experimental context \n\n- In-house DIA spike-in study to illustrate the analysis (subset of [@Staes2024]). \n- spiked digested UPS proteins in yeast background at the following ratio's \n$\\rightarrow$ yeast:ups ratio 10:1, 10:2, 10:4, 10:8, 10:10\n\n- Each sample was analyzed in triplicate \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/cptacLayoutLudger.png){width=50%}\n:::\n:::\n\n\n- Here use the data from the middle 3 spike-in ratio's (10:2, 10:4 and 10:8) \n- Searched using DIA-NN 2.2.0.\n\n## Precursor Filtering\n\n- Remove questionable identifications: Low ID Q-value, Decoys, Contaminants, ...\n- Only keep Proteotypic precursors\n- Remove precursors/PSMs with many missing values\n- ...\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenMissingness.jpg)\n:::\n:::\n\n\n**[Bourgon *et al.* (2010)](https://www.pnas.org/content/107/21/9546) showed that filtering is only appropriate if the statistic used for filtering is independent of the statistic used for hypothesis testing under the null hypothesis.**\n\n## Log-transformation\n\n- Precursor: ADSRDPASDQMQHWK, charge-state 3 from UPS|P04040ups|CATA_HUMAN_UPS\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenLogNeed.jpg)\n:::\n:::\n\n\nPlot upon log2 -transformation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenLog.jpg)\n:::\n:::\n\n\n- Mean-variance relation $\\rightarrow$ Solved by log2 tranformation\n- Other property of log transformation: \n\n$$log_2FC_{b-a} = log_2b - log_2a = log_2 \\frac{b}{a}$$\n\n## Normalisation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenNormNeeded.jpg)\n:::\n:::\n\n\nEven in clean synthetic data set $\\rightarrow$ marginal precursor intensity\ndistributions across samples not well aligned. \n\n$\\rightarrow$ Can cause power loss  & bias \n\n### Median centering\n\n- Is a popular choice \n- Often works well in very clean datasets \n- But more advance normalisation often needed in real data. \n\n#### Spike-in\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenNormMedian.jpg)\n:::\n:::\n\n\n#### Heart Example: Median Normalisation\n\n- PXD006675 on PRIDE: Doll S, Dre, B, en M, Geyer PE, Itzhak DN, Braun C, Doppler SA, Meier F, Deutsch MA, Lahm H, Lange R, Krane M, Mann M, Region and cell-type resolved quantitative proteomic map of the human heart. Nat Commun, 8(1):1469(2017)\n\n- 3 patients\n- proteomes from biopsies of atrium and ventriculum in the left\nand the right heart region \n- DDA\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenHeartNormalisationEffect.jpg)\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenHeartMedian.jpg)\n:::\n:::\n\n\n\nWhy? \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenHeartMissingness.jpg)\n:::\n:::\n\n\nMedian Normalisation \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenHeartNormalisationExplainedMedian.jpg)\n:::\n:::\n\n\n### Median of Ratios method \n\n- Borrowed from DESeq2: originally developed for RNA-seq data analysis \n- Also correct for differences in \ncomposition of the proteomes in the different samples.\n\nThe method: \n\n1. Calculates pseudo-reference sample (row-wise mean of log2 intensities, which corresponds to the log2 transformed geometric mean).\n2. Calculates log2 ratios of each sample w.r.t. the pseudo-reference.\n3. Column wise median of these log2 ratios is taken as the sample based normalisation factor on the log2 scale.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Illustration of the median-of-ratios normalisation on a toy example with four features and three samples. Starting from the matrix of log2 intensities (left), a pseudo-reference sample is obtained by taking the row-wise (feature-wise) mean. Log2 fold changes of every sample relative to this reference are then calculated (middle). Finally, the sample-specific normalisation factor is obtained as the median of these log2 fold changes over all features (right).](brixenLecture_files/figure-html/fig-mor-illustration-1.png){#fig-mor-illustration width=1008}\n:::\n:::\n\n#### Spike-in\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenNorm.jpg)\n:::\n:::\n\n\n#### Heart Example: Median of Ratio Normalisation\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenHeartNormalisationExplainedMedRat.jpg)\n:::\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenHeartMedRat.jpg)\n:::\n:::\n\n\n\ncompared to median normalisation:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenHeartMedian.jpg)\n:::\n:::\n\n\n\n## Summarisation\n\n\n- Summarise/Aggregate precursor-level intensities into a protein expression value.\n\n- Peptide-level data for\none of the spiked UPS proteins. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenSumNeed.jpg)\n:::\n:::\n\n\n\n1. Protein can consist of many precursors\n2. Huge effect of precursor species\n3. Effect of spike-in concentration\n4. Context dependent missingness\n5. Often outliers, e.g. misidentification or fluctuations during MS acquisition.\n\n\n### Median Summarisation \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenVolcanoMedRatMedian.jpg)\n:::\n:::\n\n\n- Problematic\n- Biased FC\n$\\rightarrow$ Does not account for precursor species. Missingness.\n\n\n### MaxLFQ Summarisation \n\n- Summarization should account for precursor species! \n- Popular choice: maxLFQ \n\n1. Calculates all pairwise log ratio's between samples only using their shared precursors.\nParticularly, it uses the median of the log ratio's between the shared precursors s, i.e. \n$$r_{ij} = median(y_{sj}-y_{si})$$.  \n\n2. Estimates the summaries by solving \n\n$$\n\\sum_i\\sum_j(y^{prot}_j - y^{prot}_i - r_{ij})^2\n$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenVolcanoMedRatMaxLFQ.jpg)\n:::\n:::\n\n\nWhy? \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenSummarisationExplained.jpg)\n:::\n:::\n\n\n# Statistical Modeling and Inference \n\n\n\n::: {.cell}\n\n:::\n\n\n## Motivating dataset \n\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/TW5rk1y7aOc\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/francisella.jpg){width=50%}\n:::\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/tularemia_lesion.jpg){width=50%}\n:::\n:::\n\n\n- Pathogen: causes tularemia\n- Metabolic adaptation key for intracellular life cycle of pathogenic microorganisms. \n- Upon entry into host cells quick phasomal escape and active multiplication in cytosolic compartment.\n- Franciscella is auxotroph for several amino acids, including arginine. \n- Inactivation of arginine transporter delayed bacterial phagosomal escape and intracellular multiplication. \n- Experiment to assess difference in proteome using 3 WT vs 3 ArgP KO mutants\n\n\n## Import the data in R \n\n<details><summary> Click to see code </summary><p>\n1. Load libraries \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(limma)\nlibrary(QFeatures)\nlibrary(msqrob2)\nlibrary(plotly)\nlibrary(ggplot2)\n```\n:::\n\n\n2. We use a peptides.txt file from MS-data quantified with maxquant that \ncontains MS1 intensities summarized at the peptide level. \n\n::: {.cell}\n\n```{.r .cell-code}\npeptidesFile <- \"https://raw.githubusercontent.com/statOmics/PDA22GTPB/data/quantification/francisella/peptides.txt\"\n```\n:::\n\n\n3. Maxquant stores the intensity data for the different samples in columnns that start with Intensity. We can retreive the column names with the intensity data with the code below: \n\n\n::: {.cell}\n\n```{.r .cell-code}\necols <- grep(\"Intensity\\\\.\", names(read.delim(peptidesFile)))\n```\n:::\n\n\n4. Read the data and store it in  QFeatures object \n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- readQFeatures(\n  assayData = read.delim(peptidesFile),\n  fnames = 1,\n  quantCols =  ecols,\n  name = \"peptideRaw\")\n```\n:::\n\n\n5. Update data with information on design\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolData(qf)$genotype <- qf[[1]] |> \n  colnames() |> \n  substr(12,13) |>\n  as.factor() |> \n  relevel(\"WT\")\ncolData(qf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDataFrame with 6 rows and 1 column\n                         genotype\n                         <factor>\nIntensity.1WT_20_2h_n3_3       WT\nIntensity.1WT_20_2h_n4_3       WT\nIntensity.1WT_20_2h_n5_3       WT\nIntensity.3D8_20_2h_n3_3       D8\nIntensity.3D8_20_2h_n4_3       D8\nIntensity.3D8_20_2h_n5_3       D8\n```\n\n\n:::\n:::\n\n\n</p></details>\n\n## Preprocessing\n\n<details><summary> Click to see code to log-transfrom the data </summary><p>\n\n1. Log transform\n\n  - peptides with zero intensities are missing peptides and should be represent\nwith a `NA` value rather than `0`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- zeroIsNA(qf, \"peptideRaw\") # convert 0 to NA\n```\n:::\n\n\n  - Logtransform data with base 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- logTransform(qf, base = 2, i = \"peptideRaw\", name = \"peptides_log\")\n```\n:::\n\n\n2. Filtering\n\nOnly use proteotypic proteins\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- filterFeatures(qf, ~ !grepl(pattern = \";\", Proteins))\n```\n:::\n\n\n  - Remove reverse sequences (decoys) and contaminants. Note that this is indicated by the column names Reverse and depending on the version of maxQuant with Potential.contaminants or Contaminants.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- filterFeatures(qf,~Reverse != \"+\")\nqf <- filterFeatures(qf,~ Contaminant != \"+\")\n```\n:::\n\n\n- We keep peptides that were observed at last 4 times out of the $n\n= 6$ samples, so that we can estimate the peptide characteristics. \n\nWe tolerate the following proportion of NAs:\n$\\text{pNA} = \\frac{(n - 4)}{n} = 0.33$, so we keep peptides that\nare observed in at least 66% of the samples. This is an arbitrary\nvalue that may need to be adjusted depending on the experiment and the\ndata set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnObs <- 4\nn <- ncol(qf[[\"peptides_log\"]])\n\n(qf <- filterNA(qf, i = \"peptides_log\", pNA = (n - nObs) / n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAn instance of class QFeatures (type: bulk) with 2 sets:\n\n [1] peptideRaw: SummarizedExperiment with 10461 rows and 6 columns \n [2] peptides_log: SummarizedExperiment with 5052 rows and 6 columns \n```\n\n\n:::\n:::\n\n\n\nWe keep 5052 peptides upon filtering.\n\n3. Normalization by median centering\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <-  sweep( #4. Subtract log2 norm factor column-by-column (MARGIN = 2)\n  qf,\n  MARGIN = 2, \n  STATS = nfLogMedianOfRatios(qf, i=\"peptides_log\"), #1.\n  i = \"peptides_log\",\n  name = \"peptides_norm\"\n)\n```\n:::\n\n\n\n4. Summarization. We use maxLFQ from the iq package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- aggregateFeatures(qf,\n    i = \"peptides_norm\", \n    fcol = \"Proteins\", \n    name = \"proteins\",\n    fun = function(X) iq::maxLFQ(X)$estimate\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n:::\n\n\n\nPlot of preprocessed data \n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf[, , \"peptides_norm\"] |> #1.\n  longForm(colvars = c( \"genotype\")) |>  #2. \n  data.frame() |> \n  filter(!is.na(value)) |>\n  ggplot() + #3.\n  aes(x = value,\n      colour = genotype,\n      group = colname) +\n  geom_density() +\n  theme_minimal() +\n  ggtitle(\"Peptide-level\")\n```\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n\n```{.r .cell-code}\nqf[, , \"proteins\"] |> #1.\n  longForm(colvars = c( \"genotype\")) |>  #2. \n  data.frame() |> \n  filter(!is.na(value)) |>\n  ggplot() + #3.\n  aes(x = value,\n      colour = genotype,\n      group = colname) +\n  geom_density() +\n  theme_minimal() +\n    ggtitle(\"Protein-level\")\n```\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-38-2.png){width=672}\n:::\n:::\n\n</p></details>\n\n## Summarized data structure\n\n### Design\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf |> \n  colData() |> \n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|                         |genotype |\n|:------------------------|:--------|\n|Intensity.1WT_20_2h_n3_3 |WT       |\n|Intensity.1WT_20_2h_n4_3 |WT       |\n|Intensity.1WT_20_2h_n5_3 |WT       |\n|Intensity.3D8_20_2h_n3_3 |D8       |\n|Intensity.3D8_20_2h_n4_3 |D8       |\n|Intensity.3D8_20_2h_n5_3 |D8       |\n\n\n:::\n:::\n\n\n- WT vs KO \n- 3 vs 3 repeats \n\n### Summarized intensity matrix\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf[[\"proteins\"]] |> \n  assay() |> \n  head() |> \n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|             | Intensity.1WT_20_2h_n3_3| Intensity.1WT_20_2h_n4_3| Intensity.1WT_20_2h_n5_3| Intensity.3D8_20_2h_n3_3| Intensity.3D8_20_2h_n4_3| Intensity.3D8_20_2h_n5_3|\n|:------------|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|------------------------:|\n|WP_003013731 |                 25.91971|                 26.03992|                 26.27133|                 25.93598|                 26.19855|                 26.22295|\n|WP_003013909 |                 25.87033|                 25.65042|                 25.74652|                 26.07970|                 25.90919|                 26.03624|\n|WP_003014068 |                 26.79067|                 26.76619|                 27.08102|                 26.62292|                 26.80336|                 26.77253|\n|WP_003014122 |                 25.30922|                 24.96019|                 25.18033|                 24.92020|                 24.80622|                 24.86137|\n|WP_003014123 |                 25.86714|                 25.66709|                 25.77431|                 25.70902|                 25.71849|                 25.53778|\n|WP_003014302 |                 27.85088|                 27.93109|                 27.87884|                 28.01439|                 28.02191|                 28.05122|\n\n\n:::\n:::\n\n\n- 1020 proteins \n\n## Hypothesis testing: a single protein \n\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/myP6SUlSwsM\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n### T-test\n\n\n$$\n\\text{Effect size:} \\log_2 \\text{FC} = \\bar{y}_{p1}-\\bar{y}_{p2}\n$$\n\n$$\nT_g=\\frac{\\log_2 \\widehat{\\text{FC}}}{\\text{se}_{\\log_2 \\widehat{\\text{FC}}}}\n$$\n\n$$\nT_g=\\frac{\\widehat{\\text{signal}}}{\\widehat{\\text{Noise}}}\n$$\n\nIf we can assume equal variance in both treatment groups:\n\n$$\n\\text{se}_{\\log_2 \\text{FC}}=\\text{SD}\\sqrt{\\frac{1}{n_1}+\\frac{1}{n_2}}\n$$\n\n### Linear model \n\n$$\n\\begin{array}{lcl}\ny_i &=& \\beta_0 + \\beta_{D8}x_{i,D8} + \\epsilon_i\\\\\n\\epsilon_i &\\sim& N(0,\\sigma^2)\\\\\n\\end{array}\n$$\n- $x_{i,D8}$ is dummy variable\n\n$$\n\\begin{array}{lcl}\nx_{i,D8} &=& 0 \\text{ (WT)}\\\\\nx_{i,D8} &=& 1 \\text{ (D8)}\n\\end{array}\n$$\n- $\\log_2$ FC?\n\n$$\n\\begin{array}{lcl}\n\\hat \\mu_{WT} &=& \\hat\\beta_0 \\\\  \n\\hat \\mu_{D8} &=& \\hat\\beta_0 + \\hat{\\beta}_{D8}\\\\\n\\log_2 \\widehat{\\text{FC}} &=& \\hat{\\beta}_{D8}\n\\end{array}\n$$\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\nIn R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm1  <- lm(intensity ~ genotype, data = WP_003023392)\nsummary(lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = intensity ~ genotype, data = WP_003023392)\n\nResiduals:\n       1        2        3        4        5        6 \n 0.07266 -0.12677  0.05411  0.03622 -0.15565  0.11943 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 26.10746    0.07308  357.27 3.68e-10 ***\ngenotypeD8  -1.36902    0.10334  -13.25 0.000188 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1266 on 4 degrees of freedom\nMultiple R-squared:  0.9777,\tAdjusted R-squared:  0.9721 \nF-statistic: 175.5 on 1 and 4 DF,  p-value: 0.0001877\n```\n\n\n:::\n:::\n\n\n\n$$\nt=\\frac{\\log_2\\widehat{\\text{FC}}}{\\text{se}_{\\log_2\\widehat{\\text{FC}}}}=\\frac{-1.37}{0.103}=-13.2\n$$\n\n- Is t = -13.2 indicating that\nthere is an effect?\n\n- How likely is it to observe\nt = -13.2 when there is no effect of the argP KO on the protein expression?\n\n### Null hypothesis ($H_0$) and alternative hypothesis ($H_1$)\n\n- With data we can never prove a hypothesis (falsification principle of Popper)\n- With data we can only reject a hypothesis \n\n- In general we start from *alternative hypothese* $H_1$: we want to show an effect of the KO on abundance of a protein\n\n<center>\n$H_1$: On average the protein abundance in WT is different from that in KO\n</center>\n\n- But, we will assess this by falsifying the opposite: \n<center>\n$H_0$: On average the protein abundance in WT is equal to that in KO<-\n</center>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm1 <- lm(intensity ~ genotype, data = WP_003023392)\nsummary(lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = intensity ~ genotype, data = WP_003023392)\n\nResiduals:\n       1        2        3        4        5        6 \n 0.07266 -0.12677  0.05411  0.03622 -0.15565  0.11943 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 26.10746    0.07308  357.27 3.68e-10 ***\ngenotypeD8  -1.36902    0.10334  -13.25 0.000188 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1266 on 4 degrees of freedom\nMultiple R-squared:  0.9777,\tAdjusted R-squared:  0.9721 \nF-statistic: 175.5 on 1 and 4 DF,  p-value: 0.0001877\n```\n\n\n:::\n:::\n\n\n- How likely is it to observe an equal or more extreme effect than the one observed in the sample when the null hypothesis is true?\n- When we make assumptions about the distribution of our test statistic we can quantify this probability: *p-value*. \nThe p-value will only be calculated correctly if the underlying assumptions hold!\n- When we repeat the experiment, the probability to observe a fold change for this protein that is more extreme than a 2.58 fold ($\\log_2 FC=-1.37$) down or up regulation by random change (if $H_0$ is true) is 2 out of 10000.  \n- If the p-value is below a significance threshold $\\alpha$ we reject the null hypothesis. *We control the probability on a false positive result at the $\\alpha$-level (type I error)*\n\n- Note, that the p-values are uniform under the null hypothesis, i.e. when $H_0$ is true all p-values are equally likely. \n\n## Multiple hypothesis testing\n\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/cLn-CFyA6ps\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\n\n- Consider testing DA for all $m=1020$ proteins simultaneously\n- What if we assess each individual test at level $\\alpha$?\n$\\rightarrow$ Probability to have a false positive (FP) among all m simultatenous\ntest $>>>  \\alpha= 0.05$\n\n- Indeed for each non DA protein we have a probability of 5% to return a FP.\n- In a typical experiment the majority of the proteins are non DA. \n- So an upperbound of the expected FP is $m \\times \\alpha$ or $1020 \\times 0.05=51$. \n\n$\\rightarrow$ Hence, we are bound to call many false positive proteins each time we run the experiment.\n\n### Multiple testing: False discovery rate\n\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/envDqvEwRcc\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\n\n- FDR: Expected proportion of false positives on the total number of positives you return.\n- An FDR of 1% means that on average we expect 1% false positive proteins in the list of proteins that are called significant.\n- Defined by Benjamini and Hochberg in their seminal paper Benjamini, Y. and Hochberg, Y. (1995). \"Controlling the false discovery rate: a practical and powerful approach to multiple testing\". Journal of the Royal Statistical Society Series B, 57 (1): 289–300. \n\nThe **False Discovery Proportion (FDP)** is the fraction of false positives that are returned, i.e. \n\n$$\nFDP = \\frac{FP}{R}\n$$\n\n- However, this quantity cannot be observed because in practice we only know the number of proteins for which we rejected $H_0$, $R$. \n- But, we do not know the number of false positives, $FP$.\n\nTherefore, Benjamini and Hochberg, 1995, defined The **False Discovery Rate (FDR)** as\n$$\n   \\text{FDR} = \\text{E}\\left[\\frac{FP}{R}\\right] =\\text{E}\\left[\\text{FDP}\\right]\n$$\nthe expected FDP. \n\n- Controlling the FDR allows for more discoveries (i.e. longer lists with significant results), while the fraction of false discoveries among the significant results in well controlled on average. As a consequence, more of the true positive hypotheses will be detected.\n\n\n#### Intuition of BH-FDR procedure\n\nConsider $m = 1000$ tests\n\n- Suppose that a researcher rejects all null hypotheses for which $p < 0.01$. \n\n- If we use $p < 0.01$, we expect $0.01 \\times m_0$ tests to return false positives. \n- A conservative estimate of the number of false positives that we can expect can be obtained by considering that the null hypotheses are true for all features, $m_0 = m =  1000$. \n- We then would expect $0.01 \\times 1000 = 10$ false positives ($FP=10$).\n\n- Suppose that the researcher found 200 proteins with $p<0.01$ ($R=200$).\n\n- The proportion of false positive results (FDP = false positive proportion) among the list of $R=200$ proteins can then be estimated as\n\n$$\n   \\widehat{\\text{FDP}}=\\frac{\\widehat{FP}}{R}=\\frac{10}{200}=\\frac{0.01 \\times 1000}{200} = 0.05.\n$$\n\n\n#### Benjamini and Hochberg (1995) procedure for controlling the FDR at $\\alpha$\n\n1. Let $p_{(1)}\\leq \\ldots \\leq p_{(m)}$ denote the ordered $p$-values.\n\n2. Find the largest integer $k$ so that \n$$\n\\frac{p_{(k)} \\times m}{k} \\leq \\alpha\n$$\n$$\\text{or}$$\n$$\np_{(k)} \\leq k \\times \\alpha/m\n$$\n\n3. If such a $k$ exists, reject the $k$ null hypotheses associated with $p_{(1)}, \\ldots, p_{(k)}$.\nOtherwise none of the null hypotheses is rejected.\n\nThe adjusted $p$-value (also known as the $q$-value in FDR literature):\n $$\n   q_{(i)}=\\tilde{p}_{(i)} = \\min\\left[\\min_{j=i,\\ldots, m}\\left(m p_{(j)}/j\\right), 1 \\right].\n $$\n In the hypothetical example above: $k=200$, $p_{(k)}=0.01$, $m=1000$ and $\\alpha=0.05$.\n\n#### Francisella Example\n\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/B3BmnOLkYg4\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\n<details><summary> Click to see code </summary><p>\n\n::: {.cell}\n\n```{.r .cell-code}\nttestMx <- function(y,group) {\n    test <- try(t.test(y[group],y[!group],var.equal=TRUE),silent=TRUE)\n    if(is(test,\"try-error\")) {\n      return(c(log2FC=NA,se=NA,tstat=NA,p=NA))\n      } else {\n      return(c(log2FC= (test$estimate%*%c(1,-1)),se=test$stderr,tstat=test$statistic,pval=test$p.value))\n      }\n }\n \n res <- apply(\n    assay(qf[[\"proteins\"]]), \n    1, \n    ttestMx,\n    group = colData(qf)$genotype==\"D8\") |> \n  t()\n colnames(res) <- c(\"logFC\",\"se\",\"tstat\",\"pval\")\n res <- res |> \n   as.data.frame() |> \n   na.exclude() |> \n   arrange(pval)\n res$adjPval <- p.adjust(res$pval, \"fdr\")\n alpha <- 0.05\nres$adjAlphaForm <- paste0(1:nrow(res),\" x \",alpha,\"/\",nrow(res))\nres$adjAlpha <- alpha * (1:nrow(res))/nrow(res) \nres$\"pval < adjAlpha\" <- res$pval < res$adjAlpha \nres$\"adjPval < alpha\" <- res$adjPval < alpha \n```\n:::\n\n</p></details>\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|             |      logFC|      pval|   adjPval|adjAlphaForm   |  adjAlpha|pval < adjAlpha |adjPval < alpha |\n|:------------|----------:|---------:|---------:|:--------------|---------:|:---------------|:---------------|\n|WP_003034781 |  0.4224142| 0.0000022| 0.0022721|1 x 0.05/1020  | 0.0000490|TRUE            |TRUE            |\n|WP_003040849 | -1.2263612| 0.0000076| 0.0026390|2 x 0.05/1020  | 0.0000980|TRUE            |TRUE            |\n|WP_011733723 | -0.3258931| 0.0000078| 0.0026390|3 x 0.05/1020  | 0.0001471|TRUE            |TRUE            |\n|WP_003041244 |  0.2057070| 0.0000791| 0.0201736|4 x 0.05/1020  | 0.0001961|TRUE            |TRUE            |\n|WP_003038430 | -0.3836478| 0.0001838| 0.0280097|5 x 0.05/1020  | 0.0002451|TRUE            |TRUE            |\n|WP_003023392 | -1.3690155| 0.0001877| 0.0280097|6 x 0.05/1020  | 0.0002941|TRUE            |TRUE            |\n|WP_011733588 | -0.3823744| 0.0001922| 0.0280097|7 x 0.05/1020  | 0.0003431|TRUE            |TRUE            |\n|WP_011733645 |  0.3040827| 0.0002362| 0.0301195|8 x 0.05/1020  | 0.0003922|TRUE            |TRUE            |\n|WP_004339068 |  0.1975424| 0.0006535| 0.0730468|9 x 0.05/1020  | 0.0004412|FALSE           |FALSE           |\n|WP_003018840 | -0.5013825| 0.0007161| 0.0730468|10 x 0.05/1020 | 0.0004902|FALSE           |FALSE           |\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n...\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|             |           |          |          |                 |         |      |      |\n|:------------|----------:|---------:|---------:|:----------------|--------:|:-----|:-----|\n|WP_003022463 | -0.0003682| 0.9989893| 0.9999324|1019 x 0.05/1020 | 0.049951|FALSE |FALSE |\n|WP_003033335 | -0.0000299| 0.9999324| 0.9999324|1020 x 0.05/1020 | 0.050000|FALSE |FALSE |\n\n\n:::\n:::\n\n\n\n\n\n#### Results\n\n<details><summary> Click to see code </summary><p>\n\n::: {.cell}\n\n```{.r .cell-code}\nvolcanoT <- plotVolcano(res) \n```\n:::\n\n</p></details>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvolcanoT\n```\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\n## Moderated Statistics\n\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/_Q11LXDy0xU\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\n\nProblems with ordinary t-test\n\n<details><summary> Click to see code </summary><p>\n\n::: {.cell}\n\n```{.r .cell-code}\nproblemPlots <- list() \nproblemPlots[[1]] <- res |> \n  ggplot(aes(x = logFC, y = se, color = adjPval < 0.05)) +\n    geom_point(cex = 2.5) +\n    scale_color_manual(values = alpha(c(\"black\", \"red\"), 0.5)) +\n    theme_minimal() \n\nfor (i in 2:3)\n{\nproblemPlots[[i]] <- colData(qf) |> \n    as.data.frame() |> \n    mutate(intensity = qf[[\"proteins\"]][rownames(res)[i],] |> \n             assay() |> \n             c()) |> \n    ggplot(aes(x=genotype,y=intensity)) +\n    geom_point() + \n    ggtitle(rownames(res)[i]) +\n    ylim(c(25.8,27.4)) +\n      theme_minimal() \n}\n```\n:::\n\n</p></details>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproblemPlots\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[2]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-50-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[3]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-50-3.png){width=672}\n:::\n:::\n\n\n### Empirical Bayes \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/limmaShrinkage.png){width=50%}\n:::\n:::\n\n\nFigure courtesy to Rafael Irizarry\n\n$$\n   T_p^{mod} = \\frac{\\log_2 \\widehat{\\text{FC}}\n}{C \\quad \\tilde{S}_p} ,\n $$\n\n- **empirical Bayes** theory provides formal framework for borrowing strength across proteins,\n- Implemented in popular bioconductor package **limma** and **msqrob2**\n\n$$\n  \\tilde{S}_p=\\sqrt{\\frac{d_pS_p^2+d_0S_0^2}{d_p+d_0}},\n$$\n\n- $S_0^2$: common variance (over all proteins) \n- Moderated t-statistic is t-distributed with $d_0+d_p$ degrees of freedom. \n- Note that the degrees of freedom increase by borrowing strength across proteins!\n\n<details><summary> Click to see the code </summary><p>   \n\n1. We model the protein level expression values using the `msqrob` function.\nBy default `msqrob2` estimates the model parameters using robust regression.\n\nWe will model the data with a different group mean for every genotype. \nThe group is incoded in the variable `genotype` of the colData. \nWe can specify this model by using a formula with the factor `genotype` as its predictor: \n`formula = ~genotype`.\n\nNote, that a formula always starts with a symbol '~'.\n\n::: {.cell}\n\n```{.r .cell-code}\nqf <- msqrob(object = qf, i = \"proteins\", formula = ~genotype)\n```\n:::\n\n\n2. Inference \n\nWe first explore the design of the model that we specified using the the package `ExploreModelMatrix` \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ExploreModelMatrix)\nVisualizeDesign(colData(qf),~genotype)$plotlist[[1]]\n```\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-53-1.png){width=672}\n:::\n:::\n\n\nWe have two model parameters, the (Intercept) and genotypeD8. \nThis results in a model with two group means: \n\n1. For the wild type (WT) the expected value (mean) of the log2 transformed intensity y for a protein will be modelled using \n\n$$\\text{E}[Y\\vert \\text{genotype}=\\text{WT}] = \\text{(Intercept)}$$ \n\n2. For the knockout genotype D8 the expected value (mean) of the log2 transformed intensity y for a protein will be modelled using \n\n$$\\text{E}[Y\\vert \\text{genotype}=\\text{D8}] = \\text{(Intercept)} + \\text{genotypeD8}$$ \n\nThe average log2FC between D8 and WT is thus\n$$\\log_2\\text{FC}_{D8-WT}= \\text{E}[Y\\vert \\text{genotype}=\\text{D8}] - \\text{E}[Y\\vert \\text{genotype}=\\text{WT}] = \\text{genotypeD8}\n$$\n\nHence, assessing the null hypothesis that there is no differential abundance between D8 and WT can be reformulated as\n\n$$H_0:  \\text{genotypeD8}=0$$\nWe can implement a hypothesis test for each protein in msqrob2 using the code below: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nL <- makeContrast(\"genotypeD8 = 0\", parameterNames = c(\"genotypeD8\"))\nqf <- hypothesisTest(object = qf, i = \"proteins\", contrast = L)\n```\n:::\n\n\nWe can show the list with all significant DE proteins at the 5% FDR using \n\n::: {.cell}\n\n```{.r .cell-code}\nmsqrobCollect(qf[[\"proteins\"]],L) |> \n  arrange(pval) |>\n  filter(adjPval<0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                             logFC         se       df          t         pval\ngenotypeD8.WP_003040849 -1.2263612 0.08020151 6.087933 -15.290999 4.358069e-06\ngenotypeD8.WP_003023392 -1.3690155 0.11105902 6.087933 -12.326919 1.560512e-05\ngenotypeD8.WP_003033719 -1.1615474 0.12602389 5.828253  -9.216882 1.087304e-04\ngenotypeD8.WP_003026016 -0.9540456 0.11530658 6.080135  -8.273991 1.573910e-04\ngenotypeD8.WP_003033046 -0.8219170 0.10214460 5.815009  -8.046603 2.307079e-04\ngenotypeD8.WP_003038350  0.8077325 0.10952806 6.087933   7.374663 2.978545e-04\n                            adjPval   contrast      feature\ngenotypeD8.WP_003040849 0.004301414 genotypeD8 WP_003040849\ngenotypeD8.WP_003023392 0.007701128 genotypeD8 WP_003023392\ngenotypeD8.WP_003033719 0.035772317 genotypeD8 WP_003033719\ngenotypeD8.WP_003026016 0.038836240 genotypeD8 WP_003026016\ngenotypeD8.WP_003033046 0.045541744 genotypeD8 WP_003033046\ngenotypeD8.WP_003038350 0.048997070 genotypeD8 WP_003038350\n```\n\n\n:::\n:::\n\n\nWe can also visualise the results using a volcanoplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvolcano <- plotVolcano(\n    rowData(qf[[\"proteins\"]])$genotypeD8) +\n  ggtitle(\"msqrob2\")\n```\n:::\n\n</p></details>\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-57-1.png){width=672}\n:::\n:::\n\n\n- The volcano plot opens up when using the EB variance estimator\n\n-  Borrowing strength to estimate the variance using empirical Bayes solves the issue of returning proteins with a low fold change as significant due to a low variance. \n\n\n### Shrinkage of the  variance and moderated t-statistics\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-58-1.png){width=672}\n:::\n:::\n\n\n- Small variances are shrunken towards the common variance resulting in larger EB variance estimates\n- Large variances are shrunken towards the common variance resulting in smaller EB variance estimates \n- Pooled degrees of freedom of the EB variance estimator are larger because information is borrowed across proteins to estimate the variance\n\n## Plots \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-60-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-60-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-60-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-60-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-60-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-60-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-60-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-60-8.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-60-9.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-60-10.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-60-11.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](brixenLecture_files/figure-html/unnamed-chunk-60-12.png){width=672}\n:::\n:::\n\n\n# Some Concepts on Experimental Design\n\n## Random Sampling\n\n- Random sampling is closely related to the concept of the population or the scope of the study.\n\n- Based on a sample of subjects, the researchers want to come to conclusions that hold for\n\n    - all kinds of people\n    - people with hypertension\n\n- Scope of the study should be well specified before the start of the study.\n\n- Representative sample: For the statistical analysis to be valid, it is required that the subjects are selected completely at random from the population to which we want to generalize our conclusions.\n\n- Selecting completely at random from a population implies:\n    - all subjects in the population should have the same probability of being selected in the sample,\n    - the selection of a subject in the sample should be independent from the selection of the other subjects in the sample.\n\n\n## Randomisation \n\n- Make sure that groups are comparable / Avoid systematic differences between groups\n- Randomisation: treatments of interest are attributed at random to the experimental units (subjects, animals, plants, cages, ...)\n\n\n## Control\n\nGood control is nessecary \n\n$\\rightarrow$ Placebo controlled double blind experiments     \n$\\rightarrow$ Injection of control animal with blank containing same solvents, etc. \n\n## Replication / Sample size \n\nWithin an experiment: Enables to estimate uncertainty / biological variability\n\n- Replication is essential for quantifying the noise\n\n- Noise: biological and technical in nature\n\nBetween experiments: Any true finding should be reproducible\n\n- Genuine replicates include all sources of variability: technical + biological\n\n- Technical replicates are important if you assess new technologies\n\n\n<details><summary> Movie clip </summary><p><iframe width=\"560\" height=\"315\"\nsrc=\"https://www.youtube.com/embed/uELgkzDjVRY\"\nframeborder=\"0\"\nstyle=\"display: block; margin: auto;\"\nallow=\"autoplay; encrypted-media\" allowfullscreen></iframe></p></details>\n\n\n$$\n \\log_2 \\text{FC} = \\bar{y}_{p1}-\\bar{y}_{p2}\n$$\n\n$$\nT_g=\\frac{\\log_2 \\text{FC}}{\\text{se}_{\\log_2 \\text{FC}}}\n$$\n\n$$\nT_g=\\frac{\\widehat{\\text{signal}}}{\\widehat{\\text{Noise}}}\n$$\n\nIf we can assume equal variance in both treatment groups:\n\n$$\n\\text{se}_{\\log_2 \\text{FC}}=\\text{SD}\\sqrt{\\frac{1}{n_1}+\\frac{1}{n_2}}\n$$\n\n$\\rightarrow$ if number of bio-repeats increases we have a higher power!\n\n- cfr. Study of tamoxifen treated Estrogen Recepter (ER) positive breast cancer patients (tutorial)\n\n## Randomized complete block designs\n\n\n\n$$\\sigma^2= \\sigma^2_{bio}+\\sigma^2_\\text{lab} +\\sigma^2_\\text{extraction} + \\sigma^2_\\text{run} + \\ldots$$\n\n- Biological: fluctuations in protein level between mice, fluctations in protein level between cells, ...\n- Technical: cage effect, lab effect, week effect, plasma extraction, MS-run, ...\n\n## Nature methods: Points of significance - Blocking \n\n[https://www.nature.com/articles/nmeth.3005.pdf](https://www.nature.com/articles/nmeth.3005.pdf)\n\n\n### Mouse example \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/mouseTcell_RCB_design.png){width=50%}\n:::\n:::\n\nDuguet et al. (2017) MCP 16(8):1416-1432. doi: 10.1074/mcp.m116.062745\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenMouseBlockingOrigMDS.jpg)\n:::\n:::\n\n\n#### Subsampling to show impact of design \n\nCompletely randomised design (CRD):\n\n- 4 mice vs 4 mice\n- Only one cell type per mouse\n- Linear model: \n\n$$\n\\sim \\text{type}\n$$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenMouseBlockingCRD4vs4MDS.jpg)\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenMouseBlockingCRD4vs4Means.jpg)\n:::\n:::\n\n\nRandomised complete block design:\n\n- 4 mice \n- Both regulatory and ordinary T-cells per mouse\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenMouseBlockingRCB4MDS.jpg)\n:::\n:::\n\n- All treatments of interest are present within block!\n- We can estimate the effect of the treatment within block!\n- We can isolate the between block variability from the analysis using linear model:\n$$ \n\\sim \\text{type} + \\text{mouse}\n$$\n\nRCB design (blocking):\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenMouseBlockingRCB4Means.jpg)\n:::\n:::\n\n\n#### Results \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenMouseBlockingVolcano.jpg)\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./figs/brixenMouseBlockingVariances1.jpg){width=50%}\n:::\n:::\n\n\n- Advantage if block effect/variability between mice is large. Big reduction in residual errors.  \n- Otherwise loss in degrees of freedom (more model parameters have to be estimated). \n\n$$\n\\text{SD}_\\text{res} = \\sqrt{\\frac{\\sum e_i^2}{n-p}}\n$$ \n\nwith $n-p$ equals \n\n- 8-5 = 3 for RCB and \n- 8 - 2 = 6 for CRD. \n\n# Take home messages\n\n- Explore your data in every stage of the analysis\n\n- Data processing:\n\n    - Avoid imputation\n    - Filtering\n    - log2 transformation: mean-variance + log FC\n    - More advanced normalisation methods that can account for compositional differences are often needed for real data\n    - Summarisation should account for differences in precursor/peptide characteristics\n\n\n- Statistical modeling and inference: \n\n    - Carefully think about sources of variation in experiment\n    - Translate research question in contrast/effect size\n    - Multiple testing\n    - Empirical Bayes: stabilise variance estimation\n    - Critically explore results\n    \n- Experimental design:\n\n    - Thinking about experimental design and data analysis prior to the experiment is key!\n    - Random sampling\n    - Randomisation\n    - Good control\n    - Sample size \n    - Blocking: very powerful approach to isolate important sources of variability from the experiment. \n        \n        - Both biological, e.g. animal, cell culture\n        - Technical, e.g. batch effects, ... \n\n# References\n",
    "supporting": [
      "brixenLecture_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}